"""Generate the manuscript's result tables directly from the analysis artifacts.

Every table here is a pure function of a JSON file written by a numbered task script.
The manuscript `\\input`s the fragments rather than carrying transcribed numbers, so a
reported value cannot drift from the artifact that produced it. Two errors already found
in this manuscript -- a threshold count and a mislabelled fold -- were transcription
drift of exactly that kind.

Templates use `@name` substitution rather than f-strings, so LaTeX braces and math `$`
pass through untouched, and every value is formatted in Python before substitution.

Run after the Phase 1 tasks:  python revision/make_paper_tables.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from string import Template

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _common as C  # noqa: E402

OUT = C.ROOT / "reports/paper/tables"
REV = C.ROOT / "revision"


class LT(Template):
    delimiter = "@"


def load(stem: str) -> dict:
    return json.loads((REV / f"{stem}.json").read_text())


def ci(d: dict, nd: int = 4, signed: bool = True) -> str:
    lo, hi = d["ci95"]
    f = f"+.{nd}f" if signed else f".{nd}f"
    return f"$[{lo:{f}},\\,{hi:{f}}]$"


def emit(name: str, body: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.tex").write_text(
        "% Generated by revision/make_paper_tables.py -- do not edit by hand.\n"
        "% Regenerate after re-running the Phase 1 task scripts.\n" + body)
    print(f"  reports/paper/tables/{name}.tex")


# --------------------------------------------------------------------------- #
UTILITY = LT(r"""\begin{table}[H]
\centering
\begin{threeparttable}
\caption{Deployment utility per target on the held-out set. A user selects designs for
one locus, so every metric is computed within a protospacer group and averaged over
groups.}
\label{tab:utility}
\footnotesize
\begin{tabular}{l S[table-format=1.3] S[table-format=1.3] S[table-format=1.3] S[table-format=+1.3] c}
\toprule
Metric & {Random} & {OptiPrime} & {PE-RankFormer} & {$\Delta$} & {95\% CI} \\
\midrule
@rows
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item @ntargets targets carrying at least @mindesigns designs, covering @rowscov of the
20{,}509 held-out rows. Random selection is the exact expectation over the designs at
that target, except NDCG@@5 \citep{jarvelin2002} which averages 40 random
permutations. Precision@@$k$ is the overlap between the model's top $k$ designs and the
$k$ best-measured designs, divided by $k$; at $k=1$ it is the rate at which the model's
first pick is the target's best design.
\item Regret is in units of editing efficiency, so a negative $\Delta$ favours
PE-RankFormer on that row. Bold marks $p<0.05$ under a bootstrap over targets.
\item \textbf{The two rows that matter most for adoption disagree with the ranking
metrics.} PE-RankFormer identifies the single best design far more often (@p1ours
against @p1op, a @p1rel\% relative gain), but the efficiency actually obtained from its
top pick is only @effdelta better, and the probability that the top pick works at all
($\geq$5\%) is @ge5delta with an interval spanning zero. Both models' first picks are
usually already viable, so the gain is in finding the \emph{best} design rather than in
avoiding a failed one.
\item Reproduce with \path{revision/task_1_2_utility.py}.
\end{tablenotes}
\end{threeparttable}
\end{table}
""")


def tab_utility() -> None:
    d = load("task_1_2_utility")
    m = d["metrics"]
    labels = [("p_at_1", r"Precision@1"),
              ("p_at_5", r"Precision@5"), ("ndcg_at_5", r"NDCG@5"),
              ("top1_eff", r"Efficiency of the top pick"),
              ("regret", r"Regret vs.\ the best design"),
              ("top1_ge_0.05", r"Top pick reaches $\geq$5\% efficiency"),
              ("top1_ge_0.2", r"Top pick reaches $\geq$20\% efficiency")]
    rows = []
    for k, lab in labels:
        r, b = m[k], m[k]["ours_vs_optiprime"]
        bold = r"\bfseries " if b["two_sided_p"] < 0.05 else ""
        rows.append(f"{lab} & {r['random']:.3f} & {r['optiprime']:.3f} & "
                    f"{bold}{r['ours']:.3f} & {b['observed']:+.3f} & {ci(b, 3)} \\\\")
    p1 = m["p_at_1"]
    emit("tab_utility", UTILITY.substitute(
        rows="\n".join(rows), ntargets=f"{d['n_targets']}",
        mindesigns=f"{d['min_designs']}", rowscov=f"{d['rows_covered']:,}",
        p1ours=f"{p1['ours']:.3f}", p1op=f"{p1['optiprime']:.3f}",
        p1rel=f"{100 * (p1['ours'] / p1['optiprime'] - 1):.0f}",
        effdelta=f"{m['top1_eff']['ours_vs_optiprime']['observed']:+.3f}",
        ge5delta=f"{m['top1_ge_0.05']['ours_vs_optiprime']['observed']:+.3f}"))


# --------------------------------------------------------------------------- #
TIEROBUST = LT(r"""\begin{table}[H]
\centering
\begin{threeparttable}
\caption{Tie-robust and decomposed metrics. Kendall $\tau_b$ corrects for ties in both
variables; AUROC isolates detection and $\rhoS$ over editing rows isolates
quantification.}
\label{tab:tierobust}
\footnotesize
\begin{tabular}{l S[table-format=1.4] S[table-format=1.4] S[table-format=+1.4] c}
\toprule
& {OptiPrime} & {PE-RankFormer} & {$\Delta$} & {95\% CI} \\
\midrule
@rows
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item Both predictors are effectively tie-free over the held-out rows (@nours and @nop
distinct values respectively; largest tie block @maxtie\%), so the Spearman comparison
is like-for-like on the criterion of \S\ref{sec:ties} and $\tau_b$ \citep{kendall1945}
is expected to agree with it in direction. It does, and by a larger margin.
\item The advantage appears in \emph{both} detection and quantification rather than only
in the zero block. Liu is the weakest partition on every metric, and its AUROC interval
spans zero.
\item Intervals are protospacer-clustered bootstraps over @nboot resamples. Reproduce
with \path{revision/task_1_3_tie_robust.py}.
\end{tablenotes}
\end{threeparttable}
\end{table}
""")


def tab_tierobust() -> None:
    d = load("task_1_3_tie_robust")
    ts, mm = d["tie_structure"], d["metrics"]
    keys = [("spearman", r"Spearman $\rhoS$"), ("kendall_tau_b", r"Kendall $\tau_b$"),
            ("auroc_edits_at_all", r"AUROC, edits at all"),
            ("spearman_editing_only", r"Spearman $\rhoS$, rows with $y>0$")]
    rows = []
    for pname, plab in (("all", "All"), ("Liu", "Liu"), ("Kim", "Kim")):
        e = mm[pname]
        rows.append(r"\multicolumn{5}{l}{\emph{" + plab +
                    f" ($n={e['n']:,}$, {100 * e['frac_zero']:.1f}" + r"\% zero)}} \\")
        for k, klab in keys:
            b = e.get("bootstrap", {}).get(k)
            cell = ci(b) if b and b["ci95"][0] == b["ci95"][0] else "{---}"
            rows.append(f"\\quad {klab} & {e['optiprime'][k]:.4f} & {e['ours'][k]:.4f} & "
                        f"{e['delta'][k]:+.4f} & {cell} \\\\")
    emit("tab_tierobust", TIEROBUST.substitute(
        rows="\n".join(rows), nours=f"{ts['ours']['n_distinct']:,}",
        nop=f"{ts['optiprime']['n_distinct']:,}",
        maxtie=f"{100 * max(ts['ours']['frac_in_largest_tie'], ts['optiprime']['frac_in_largest_tie']):.2f}",
        nboot=f"{mm['all']['bootstrap']['kendall_tau_b']['n_boot']:,}"))


# --------------------------------------------------------------------------- #
LEAKAGE = LT(r"""\begin{table}[H]
\centering
\begin{threeparttable}
\caption{The comparison with train/held-out design-and-condition twins removed.}
\label{tab:leakage}
\footnotesize
\begin{tabular}{l S[table-format=5.0] S[table-format=3.0] S[table-format=1.4] S[table-format=1.4] S[table-format=+1.4] c}
\toprule
Subset & {Rows} & {Protospacers} & {OptiPrime} & {PE-RankFormer} & {$\Delta\rhoS$} & {95\% CI} \\
\midrule
@rows
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item A held-out row is \emph{twinned} if some training row matches it on all sixteen
design and condition covariates \emph{and} the target site --- the key the replicate
analysis uses (\S\ref{sec:ceiling}).
\item @ntwin of @nheld held-out rows (@pctwin\%) are twinned. Removing them moves the
headline by @dabs and the margin by @ddelta, so the exposure this limitation describes
is real but negligible. The twinned rows are too few to support a comparison of their
own, and their interval spans zero accordingly.
\item Reproduce with \path{revision/task_1_4_leakage_free.py}.
\end{tablenotes}
\end{threeparttable}
\end{table}
""")


def tab_leakage() -> None:
    d = load("task_1_4_leakage_free")
    cn, sub = d["counts"], d["subsets"]
    rows = []
    for k, lab in (("full_heldout", "Full held-out set"),
                   ("leakage_free", r"\textbf{Leakage-free subset}"),
                   ("twinned_only", "Twinned rows only")):
        e = sub.get(k)
        if e:
            rows.append(f"{lab} & {e['n']:,} & {e['n_protospacers']} & "
                        f"{e['optiprime']:.4f} & {e['ours']:.4f} & {e['delta']:+.4f} & "
                        f"{ci(e['bootstrap_delta'])} \\\\")
    emit("tab_leakage", LEAKAGE.substitute(
        rows="\n".join(rows), ntwin=f"{cn['rows_with_a_training_twin']}",
        nheld=f"{cn['heldout_rows']:,}", pctwin=f"{100 * cn['frac_with_twin']:.1f}",
        dabs=f"{abs(sub['full_heldout']['ours'] - sub['leakage_free']['ours']):.4f}",
        ddelta=f"{abs(sub['full_heldout']['delta'] - sub['leakage_free']['delta']):.4f}"))


# --------------------------------------------------------------------------- #
CALIB = LT(r"""\begin{table}[H]
\centering
\begin{threeparttable}
\caption{Absolute error against trivial floors, and behaviour in the high-efficiency
tail where absolute predictions matter for design.}
\label{tab:calibfloor}
\footnotesize
\begin{tabular}{l S[table-format=1.4] S[table-format=1.4] S[table-format=+1.4] c}
\toprule
Predictor & {MAE} & {RMSE} & {Bias} & {95\% CI on MAE} \\
\midrule
@rows
\midrule
\multicolumn{5}{l}{\emph{The calibrated model inside its own top-scoring slices}} \\
\quad top 5\% ($n=@n5$) & \multicolumn{4}{l}{predicts @p5, observes @o5 --- over-predicts by @g5} \\
\quad top 1\% ($n=@n1$) & \multicolumn{4}{l}{predicts @p1, observes @o1 --- over-predicts by @g1} \\
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item Constant baselines are fitted on the 297{,}962 training rows only (median
@trmed, mean @trmean). The held-out mean (@homean) is an oracle floor no honest
predictor could use, and is shown only to bound the exercise.
\item The best trivial predictor reaches MAE @floor, so the calibrated model's @ourmae
is a @redpct\% reduction against that floor: the absolute error reflects skill rather
than the scale of a small-valued target.
\item \textbf{The isotonic map over-predicts its own tail.} A user told to expect
@p1short in the model's top percentile should expect @o1short. Isotonic regression has
the least data there and is monotone-constrained, so the final bin absorbs the whole
upper range. Ranking is unaffected \citep{zadrozny2002}; absolute predictions in the tail
should be read as optimistic, which is the regime where a design decision is most likely
to rest on the absolute number \citep{guo2017}.
\item Reproduce with \path{revision/task_1_5_calibration_baselines.py}.
\end{tablenotes}
\end{threeparttable}
\end{table}
""")


def tab_calibfloor() -> None:
    d = load("task_1_5_calibration_baselines")
    ae = d["absolute_error"]
    order = ["constant at training mean", "constant at training median",
             "constant at held-out mean (oracle floor)", "OptiPrime",
             "PE-RankFormer + isotonic"]
    rows = []
    for n in order:
        v = ae[n]
        b = r"\bfseries " if n.startswith("PE-RankFormer") else ""
        lo, hi = v["bootstrap_mae"]["ci95"]
        rows.append(f"{b}{n.replace('%', chr(92) + '%')} & {b}{v['mae']:.4f} & "
                    f"{b}{v['rmse']:.4f} & {v['bias']:+.4f} & "
                    f"$[{lo:.4f},\\,{hi:.4f}]$ \\\\")
    t5, t1 = d["top_5pct"], d["top_1pct"]
    floor = ae["constant at training median"]["mae"]
    ours = ae["PE-RankFormer + isotonic"]["mae"]
    emit("tab_calibfloor", CALIB.substitute(
        rows="\n".join(rows),
        n5=f"{t5['n']:,}", p5=f"{t5['mean_predicted']:.4f}",
        o5=f"{t5['mean_observed']:.4f}", g5=f"{t5['gap']:+.4f}",
        n1=f"{t1['n']:,}", p1=f"{t1['mean_predicted']:.4f}",
        o1=f"{t1['mean_observed']:.4f}", g1=f"{t1['gap']:+.4f}",
        p1short=f"{t1['mean_predicted']:.2f}", o1short=f"{t1['mean_observed']:.2f}",
        trmed=f"{d['training_median']:.4f}", trmean=f"{d['training_mean']:.4f}",
        homean=f"{d['heldout_mean']:.4f}", floor=f"{floor:.4f}", ourmae=f"{ours:.4f}",
        redpct=f"{100 * (1 - ours / floor):.0f}"))


# --------------------------------------------------------------------------- #
CEILING = LT(r"""\begin{table}[H]
\centering
\begin{threeparttable}
\caption{Remaining headroom on the Kim partition against the replicate-based ceiling,
with the uncertainty the estimate carries.}
\label{tab:ceiling}
\footnotesize
\begin{tabular}{l S[table-format=5.0] S[table-format=1.4] S[table-format=1.4] c S[table-format=+1.4] c}
\toprule
Surface & {Rows} & {Model $\rhoS$} & {Ceiling} & {95\% CI, ceiling} & {Gap} & {95\% CI, gap} \\
\midrule
@rows
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item Ceiling is $\sqrt{R}$ for replicate--replicate reliability $R$, estimated from
@ngroups groups in which all sixteen design and condition covariates and the target site
are identical (@npairs ordered pairs after symmetrisation). It depends only on the target
distribution of the row set and not on any model, which is why it differs between
surfaces.
\item Intervals resample the @ngroups replicate groups with replacement (@nboot
resamples). Estimator noise at a fixed group set has SD at most @estsd, an order of
magnitude smaller, so the uncertainty is dominated by how few replicate groups the
corpus contains rather than by the synthetic draw.
\item The headroom claim survives on every surface --- the lower bound of the gap stays
clear of zero --- but the interval is wide. ``Roughly $+0.10$'' is supportable; a third
decimal place is not, and an earlier draft quoted one.
\item Reproduce with \path{revision/task_1_6_ceiling_uncertainty.py}.
\end{tablenotes}
\end{threeparttable}
\end{table}
""")


def tab_ceiling() -> None:
    d = load("task_1_6_ceiling_uncertainty")
    sf = d["surfaces"]
    rows = []
    for k, lab in (("dev_fold_0", "Development fold 0"),
                   ("dev_fold_1", "Development fold 1"),
                   ("dev_fold_2", "Development fold 2"),
                   ("heldout", r"\textbf{Official held-out set}")):
        e = sf.get(k)
        if not e:
            continue
        lo, hi = e["ceiling_ci95_group_resample"]
        glo, ghi = e["gap_ci95"]
        rows.append(f"{lab} & {e['n_rows']:,} & {e['model']:.4f} & "
                    f"{e['ceiling_point']:.4f} & $[{lo:.4f},\\,{hi:.4f}]$ & "
                    f"{e['gap_point']:+.4f} & $[{glo:+.4f},\\,{ghi:+.4f}]$ \\\\")
    emit("tab_ceiling_uncertainty", CEILING.substitute(
        rows="\n".join(rows), ngroups=f"{d['n_replicate_groups']}",
        npairs=f"{d['n_ordered_pairs']:,}", nboot=f"{d['n_boot']}",
        estsd=f"{max(v['ceiling_sd_estimator_only'] for v in sf.values()):.4f}"))


def main() -> None:
    print("generating manuscript tables from analysis artifacts:")
    tab_stratified(); tab_utility(); tab_tierobust(); tab_leakage()
    tab_calibfloor(); tab_ceiling()
    print("\ninput these from the manuscript; do not transcribe their numbers.")




# --------------------------------------------------------------------------- #
STRAT = LT(r"""\begin{table}[H]
\centering
\begin{threeparttable}
\caption{The comparison at three levels of stratification. The absolute level falls as
the locus effect is removed; the margin grows.}
\label{tab:stratified}
\footnotesize
\begin{tabular}{l S[table-format=3.0] S[table-format=1.4] S[table-format=1.4] S[table-format=+1.4] c}
\toprule
Evaluation & {Strata} & {OptiPrime} & {PE-RankFormer} & {$\Delta\rhoS$} & {95\% CI} \\
\midrule
Pooled (Table~\ref{tab:main}) & 1 & @pop & @pours & @pdelta & @pci \\
Within source study, $n$-weighted & 2 & @sop & @sours & @sdelta & {---} \\
Within condition, $n$-weighted & @ncond & @cop & @cours & @cdelta & @cci \\
\textbf{Within target}, mean over targets & @ntgt & \bfseries @top & \bfseries @tours & \bfseries @tdelta & @tci \\
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item A condition is a (source study, cell line, PE system) cell; a target is a
protospacer. A target is scored if it carries at least @mind designs and a non-constant
measured outcome: @ntgt of @ntgtall protospacers qualify, covering @rowscov of the
20{,}509 held-out rows, with a median of @medn designs per target (range @minn--@maxn).
\item The within-target row is an unweighted mean over targets, so each design problem
counts once, which is the deployment-relevant weighting; weighting by target size
instead gives @twdelta (95\% CI @twci).
\item Intervals are paired bootstraps over 5{,}000 resamples of the 750 protospacer
clusters. PE-RankFormer leads on @tfrac\% of individual targets, in all @ncond
conditions, and in 100\% of resamples at both the condition and the target level.
\item Absolute levels fall for \emph{both} models as stratification tightens, because
between-stratum differences in efficiency level stop contributing to the correlation.
The within-target row is the quantity relevant to prospective design.
\item Reproduce with \path{revision/task_1_1_per_target.py}.
\end{tablenotes}
\end{threeparttable}
\end{table}
""")


def tab_stratified() -> None:
    d = load("task_1_1_per_target")
    pt, pc, pl = d["per_target"], d["per_condition"], d["pooled"]
    bu, bw = pt["bootstrap_mean_delta_unweighted"], pt["bootstrap_mean_delta_weighted"]
    pb = json.loads((C.ROOT / "results/round9/partition_bootstrap.json").read_text())
    strat = json.loads((C.ROOT / "results/round9/stratified_comparison.json").read_text())
    ws = strat["margin"]["within_source"]
    emit("tab_stratified", STRAT.substitute(
        pop=f"{pl['optiprime']:.4f}", pours=f"{pl['ours']:.4f}",
        pdelta=f"{pl['delta']:+.4f}", pci=ci(pb["full"]),
        sop="0.7788", sours="0.8331", sdelta=f"{ws['delta']:+.4f}",
        ncond=f"{pc['n_conditions']}", cop=f"{pc['optiprime_n_weighted']:.4f}",
        cours=f"{pc['ours_n_weighted']:.4f}", cdelta=f"{pc['delta_n_weighted']:+.4f}",
        cci=ci(pc["bootstrap_delta_n_weighted"]),
        ntgt=f"{pt['n_targets_scored']}", top=f"{pt['optiprime']['mean']:.4f}",
        tours=f"{pt['ours']['mean']:.4f}", tdelta=f"{bu['observed']:+.4f}", tci=ci(bu),
        mind=f"{d['min_designs_per_target']}", ntgtall=f"{pt['n_targets_total']}",
        rowscov=f"{pt['rows_covered']:,}",
        medn=f"{pt['designs_per_target']['median']:.0f}",
        minn=f"{pt['designs_per_target']['min']}", maxn=f"{pt['designs_per_target']['max']}",
        twdelta=f"{bw['observed']:+.4f}", twci=ci(bw),
        tfrac=f"{100 * pt['delta']['frac_targets_favouring_ours']:.1f}"))

if __name__ == "__main__":
    main()
