"""Build data/processed/hsu2026_74769.parquet and reports/hsu_data_validation.md."""

from __future__ import annotations

import argparse
import hashlib
import logging
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from pe_rankformer.data.hsu2026 import (  # noqa: E402
    CONTEXTS,
    EXPECTED_TOTAL,
    count_efficiencies,
    load_hsu2026,
)
from pe_rankformer.data.seqops import revcomp  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("build_hsu2026")

DEFAULT_WORKBOOK = Path("data/raw/hsu2026/41587_2026_3261_MOESM3_ESM.xlsx")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _quality_checks(table: pd.DataFrame) -> dict[str, object]:
    eff = table["editing_efficiency"]
    pbs_matches = [
        revcomp(pbs) in wt
        for pbs, wt in zip(table["pbs_sequence"], table["unedited_sequence"])
    ]
    return {
        "n_rows": len(table),
        "n_designs": table[["source_dataset", "source_row_id"]].drop_duplicates().shape[0],
        "n_protospacers": int(table["protospacer"].nunique()),
        "n_targets": int(table["target_id"].nunique()),
        "protospacer_missing": int(table["protospacer"].isna().sum()),
        "pam_missing": int(table["pam"].isna().sum()),
        "pam_ngg_fraction": float(table["pam"].dropna().str[1:].eq("GG").mean()),
        "efficiency_min": float(eff.min()),
        "efficiency_max": float(eff.max()),
        "efficiency_mean": float(eff.mean()),
        "efficiency_out_of_unit_range": int(((eff < 0) | (eff > 1)).sum()),
        "efficiency_missing": int(eff.isna().sum()),
        "indel_missing": int(table["indel_rate"].isna().sum()),
        "pbs_anneals_to_target_fraction": float(pd.Series(pbs_matches).mean()),
        "duplicate_record_ids": int(table["record_id"].duplicated().sum()),
    }


def _write_report(
    path: Path,
    workbook: Path,
    digest: str,
    counts: list,
    table: pd.DataFrame,
    checks: dict[str, object],
    parquet_path: Path,
    parquet_digest: str,
) -> None:
    lines: list[str] = []
    a = lines.append
    a("# Hsu et al. 2026 data validation\n")
    a(f"Source workbook: `{workbook}`  \nSHA256: `{digest}`\n")
    a("Generated by `scripts/data/build_hsu2026.py`.\n")

    a("## 1. How the 74,769 measurements were obtained\n")
    a(
        "The workbook holds two screening libraries, `Supp Table 4 LibMMR` (Lib-MMR) and\n"
        "`Supp Table 5 LibCV` (Lib-CV). Each sheet has one row per pegRNA design and eight\n"
        "measurement columns: `{HEK293T,HeLa}_{PE2,PE4}_{editing,indel}`. Melting the four\n"
        "`*_editing` columns gives one row per (design, experimental context) pair, and the\n"
        "**only** filter applied is that the editing value is present. No thresholding on\n"
        "read counts, efficiency, indel rate, edit type or design category is applied.\n"
    )

    a("### Per-context nonmissing editing measurements\n")
    header = " | ".join(prefix for prefix, _, _ in CONTEXTS)
    a(f"| Sheet | designs | {header} | subtotal |")
    a("|---|---:|" + "---:|" * (len(CONTEXTS) + 1))
    for c in counts:
        cells = " | ".join(f"{c.per_context[p]:,}" for p, _, _ in CONTEXTS)
        a(f"| {c.dataset} | {c.n_designs:,} | {cells} | {c.total:,} |")
    grand = sum(c.total for c in counts)
    a(f"| **Total** | {sum(c.n_designs for c in counts):,} | | | | | **{grand:,}** |\n")
    a(f"Expected {EXPECTED_TOTAL:,}; obtained {grand:,}; difference {grand - EXPECTED_TOTAL}.\n")

    a("## 2. Canonical schema and orientation\n")
    a(
        "* `unedited_sequence` / `edited_sequence`: `Designed target (ps-pam-edit)` and its\n"
        "  edited counterpart, i.e. the protospacer strand 5'->3' with protospacer, then PAM,\n"
        "  then the edit region. Lib-CV supplies `unedited_target` / `edited_target` in the\n"
        "  same orientation.\n"
        "* `protospacer`: located inside `unedited_sequence` by searching for the designed\n"
        "  spacer, and for the spacer minus a non-genomic 5' G when the full spacer is absent.\n"
        "* `pam`: the three bases immediately 3' of the protospacer.\n"
        "* `pbs_sequence` / `rtt_sequence`: pegRNA orientation 5'->3'. Lib-MMR gives the\n"
        "  extension as `PBS + edit product + homology arm` on the protospacer strand, so\n"
        "  `pbs_sequence = revcomp(PBS)` and `rtt_sequence = revcomp(edit product + homology arm)`.\n"
        "  Lib-CV gives `pbs_bind`, `edit_product` and `homology_arm` directly; the same rule\n"
        "  reproduces its `extension` column exactly.\n"
        "* `edit_type` / `edit_length` / `edit_position`: derived by stripping the shared\n"
        "  prefix and suffix of the WT and edited sequences, not by trusting a design label.\n"
        "* `edit_position_from_nick`: edit start minus the nick position, where the nick lies\n"
        "  3 nt 5' of the PAM (after protospacer base 17).\n"
        "* `scaffold_type` and `epegRNA_flag` are left null: the workbook does not record them\n"
        "  for the library screens, and the spec forbids inventing metadata.\n"
    )

    a("## 3. Quality control\n")
    a("| Check | Value |")
    a("|---|---:|")
    for k, v in checks.items():
        a(f"| `{k}` | {v:,.6g} |" if isinstance(v, float) else f"| `{k}` | {v:,} |")
    a("")
    a(
        "`pbs_anneals_to_target_fraction` verifies that the reverse complement of each\n"
        "pegRNA PBS occurs inside the unedited target, which independently confirms the\n"
        "orientation convention. `pam_ngg_fraction` checks the expected NGG PAM.\n"
    )

    a("## 4. Composition\n")
    for col in ("source_dataset", "cell_type", "prime_editor", "edit_type"):
        a(f"### by `{col}`\n")
        a("| value | n |")
        a("|---|---:|")
        for value, n in table[col].value_counts().items():
            a(f"| {value} | {n:,} |")
        a("")

    a("### by design category\n")
    a("| category | n |")
    a("|---|---:|")
    for value, n in table["design_category"].value_counts().items():
        a(f"| {value} | {n:,} |")
    a("")

    a("## 5. Output\n")
    a(f"`{parquet_path}`  \nSHA256: `{parquet_digest}`  \nRows: {len(table):,}\n")

    path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workbook", type=Path, default=DEFAULT_WORKBOOK)
    ap.add_argument("--out", type=Path, default=Path("data/processed/hsu2026_74769.parquet"))
    ap.add_argument("--report", type=Path, default=Path("reports/hsu_data_validation.md"))
    args = ap.parse_args()

    digest = sha256(args.workbook)
    logger.info("workbook sha256 %s", digest)

    counts = count_efficiencies(args.workbook)
    grand = sum(c.total for c in counts)
    for c in counts:
        logger.info("%s: %d designs, %d measurements", c.dataset, c.n_designs, c.total)
    logger.info("total measurements %d (expected %d)", grand, EXPECTED_TOTAL)

    table = load_hsu2026(args.workbook)
    if len(table) != EXPECTED_TOTAL:
        raise SystemExit(f"expected {EXPECTED_TOTAL} rows, built {len(table)}")

    checks = _quality_checks(table)
    for k, v in checks.items():
        logger.info("check %s = %s", k, v)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    table.to_parquet(args.out, index=False)
    parquet_digest = sha256(args.out)
    logger.info("wrote %s (%d rows) sha256 %s", args.out, len(table), parquet_digest)

    args.report.parent.mkdir(parents=True, exist_ok=True)
    _write_report(
        args.report, args.workbook, digest, counts, table, checks, args.out, parquet_digest
    )
    logger.info("wrote %s", args.report)


if __name__ == "__main__":
    main()
