"""LaTeX tables for reports/adaptation_report.tex, from E25–E32 artifacts.

Numbers are read from experiment JSON. This guards transcription, not interpretation
or experimental validity; head identity and evaluation exposure must remain explicit.

Usage: .venv/bin/python explore_v2/make_adapt_tables.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "reports" / "tables_adapt"
HDR = "% generated by explore_v2/make_adapt_tables.py -- do not edit by hand\n"
NO = r"\textbf{no}"


def pct(x: float) -> str:
    """A percentage safe to place in a LaTeX S column."""
    return f"{100 * x:+.1f}"

WHAT = {
    "P": ("head, pooling, cross-attn, last block", "native ordinal (prediction)"),
    "S": ("same, plus a selection head", "smooth expected regret"),
    "M": ("same, both heads", "ordinal $+$ selection"),
    "Z": ("selection head only, encoder frozen", "smooth expected regret"),
    "shared": ("same as M, capacity in the trunk", "ordinal $+$ selection, one score"),
    "G": ("geometry MLP only, no sequence model", "smooth expected regret"),
    "Sgeom": ("as S, geometry made explicit", "smooth expected regret"),
    "S|listnet": ("as S", "listwise cross-entropy"),
    "S|pairwise": ("as S", "utility-weighted pairwise"),
}


def load(stem):
    p = HERE / f"{stem}.json"
    return json.loads(p.read_text()) if p.exists() else None


def w(name, body):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(HDR + body)
    print("wrote", (OUT / name).relative_to(HERE.parent))


def arm_of(n):
    m = re.match(r"([A-Za-z]+)(?:_(n\d+|listnet|pairwise))?_s(\d+)$", n)
    return (m.group(1) + ("|" + m.group(2) if m.group(2) else ""), int(m.group(3)))


def tex_arm(a: str) -> str:
    """A bare `|` is not text-mode LaTeX; render the variant suffix readably."""
    return a.replace("|n", ", $n=$").replace("|", ", ")


def collect(e27):
    s = next(x for x in e27["strata"] if x["stratum"] == "all eligible")
    by = {}
    for k, v in s["arms"].items():
        if k in ("op", "ours", "rand", "oracle"):
            continue
        a, sd = arm_of(k)
        b = by.setdefault(a, {"ach": [], "reg": [], "delta": [], "p": [], "rho": [],
                              "ci": []})
        d = s["paired"][f"{k}_minus_op"]
        b["ach"].append(v["achieved_at_1"]); b["reg"].append(v["regret_at_1"])
        b["delta"].append(d["observed"]); b["p"].append(d["two_sided_p"])
        b["ci"].append(d["ci95"]); b["rho"].append(e27["pooled_spearman"][k])
    return s, by


# ------------------------------------------------------------------ partition --------
def tab_partition(e25):
    sp = e25["splits"]
    rows = [f"{k} & {v['components']:,} & {v['groups']:,} & {v['informative_groups']:,} & "
            f"{v['groups_depth_ge5']:,} & {v['candidates']:,} & "
            f"{e25['geometry_by_split'][k]['rtt_len_mean']:.2f} & "
            f"{v['mean_efficiency']:.4f} \\\\" for k, v in sp.items()]
    g = e25["graph"]
    w("tab_partition.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}\footnotesize
\caption{The adaptation partition. Whole locus components are assigned, because %s alleles
are reachable by more than one protospacer and %s protospacers install more than one allele,
so decision groups are not independent units.}
\label{tab:partition}
\begin{tabular}{l S[table-format=5.0] S[table-format=5.0] S[table-format=5.0]
                  S[table-format=4.0] S[table-format=5.0] S[table-format=2.2] S[table-format=1.4]}
\toprule
Split & {Components} & {Groups} & {Informative} & {Depth $\geq$5} & {Candidates} &
{Mean RTT} & {Mean eff.} \\
\midrule
""" % (f"{g['alleles_reached_by_multiple_protospacers']:,}",
       f"{g['protospacers_installing_multiple_alleles']:,}") + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item %s components over %s alleles and %s protospacers; %.0f\%% are singletons and the
largest holds %d groups. Assignment balances group count and depth-$\geq$5 count within
strata of edit class, depth and RTT band -- RTT because it is the geometry axis on which the
models are known to be biased, where an accidental imbalance would confound everything.
\end{tablenotes}\end{threeparttable}\end{table}
""" % (f"{g['components']:,}", f"{g['alleles']:,}", f"{g['protospacers']:,}",
       100 * g["component_size_in_groups"]["frac_singleton"],
       g["component_size_in_groups"]["max"]))


# ----------------------------------------------------------------- main result -------
def tab_test(e27):
    s, by = collect(e27)
    op, ours = s["arms"]["op"], s["arms"]["ours"]
    opreg = op["regret_at_1"]
    order = ["S|pairwise", "shared", "S|listnet", "P", "S", "M", "Sgeom", "Z", "G"]
    rows = []
    for a in order:
        if a not in by:
            continue
        b = by[a]
        n = len(b["ach"])
        sd = f"{np.std(b['ach'], ddof=1):.5f}" if n > 1 else "{--}"
        allpos = all(x > 0 for x in b["delta"])
        agree = "yes" if allpos else NO
        red = pct((opreg - np.mean(b["reg"])) / opreg)
        rows.append(f"{tex_arm(a)} & {n} & {np.mean(b['ach']):.5f} & {sd} & "
                    f"{np.mean(b['delta']):+.5f} & {agree} & {red} & "
                    f"{np.mean(b['rho']):.4f} \\\\")
    ref = [f"OptiPrime (released) & {{--}} & {op['achieved_at_1']:.5f} & {{--}} & {{--}} & "
           f"{{--}} & {{--}} & {e27['pooled_spearman']['op']:.4f} \\\\",
           f"PE-RankFormer, unadapted & {{--}} & {ours['achieved_at_1']:.5f} & {{--}} & "
           f"{s['paired']['ours_minus_op']['observed']:+.5f} & {{--}} & "
           f"{pct((opreg - ours['regret_at_1']) / opreg)} & "
           f"{e27['pooled_spearman']['ours']:.4f} \\\\",
           f"random choice & {{--}} & {s['arms']['rand']['achieved_at_1']:.5f} & {{--}} & "
           r"{--} & {--} & {--} & {--} \\",
           f"perfect chooser & {{--}} & {s['arms']['oracle']['achieved_at_1']:.5f} & {{--}} "
           r"& {--} & {--} & {--} & {--} \\"]
    cap = (r"\caption{The primary endpoint: achieved efficiency at rank 1 on the held-out "
           r"test components, " + f"{s['groups']:,}" + r" groups over " +
           f"{s['clusters']:,}" + r" locus clusters. Historical E27 results; this library "
           r"had prior exploratory use and is not independent confirmation.}")
    w("tab_test.tex",
      r"\begin{table}[htbp]\centering\begin{threeparttable}\footnotesize" "\n" + cap + "\n"
      + r"""\label{tab:test}\scriptsize
\begin{tabular}{l S[table-format=1] S[table-format=1.5] S[table-format=1.5]
                  S[table-format=+1.5] c S[table-format=+2.1] S[table-format=1.4]}
\toprule
Arm & {Seeds} & {Achieved @1} & {SD} & {$\Delta$ vs.\ OP} & {Seeds $+$} &
{Regret $\downarrow$ (\%)} & {$\rho$} \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
""" + "\n".join(ref) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item Full-budget sequence-adapted arms have per-seed locus-clustered intervals
excluding zero at $p=0.001$; G does not ($p=0.134$), and Z has $p=0.002$. ``Regret
$\downarrow$'' is the reduction of OptiPrime's regret; the plan's provisional target
was 10\%.
\item $\rho$ uses the original prediction head, while achieved @1 uses the deployed
selector. These differ for S, M and Z. Means over seeds are not score ensembles.
The unadapted reference is the published five-checkpoint ordinal-S4D ensemble,
not the single checkpoint used to initialize adaptation. Pairwise has three
validation seeds after E30, but only one historical test seed in this table.
\end{tablenotes}\end{threeparttable}\end{table}
""")


# ------------------------------------------------------------- learning curve --------
def tab_curve(e27):
    s, by = collect(e27)
    op = s["arms"]["op"]["achieved_at_1"]
    ours = s["arms"]["ours"]["achieved_at_1"]
    budgets = [("P|n200", 200), ("P|n1000", 1000), ("P|n5000", 5000), ("P", 19357)]
    rows = []
    for key, n in budgets:
        if key not in by:
            continue
        b = by[key]
        rows.append(f"{n:,} & {np.mean(b['ach']):.5f} & {np.mean(b['delta']):+.5f} & "
                    f"{np.mean(b['ach']) - ours:+.5f} & {np.mean(b['p']):.3f} \\\\")
    w("tab_curve.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}\footnotesize
\caption{Historical training-budget experiments, on the test components. Subsets take whole
decision groups, not necessarily whole locus components, and are not consistently nested.}
\label{tab:curve}
\begin{tabular}{S[table-format=5.0] S[table-format=1.5] S[table-format=+1.5]
                S[table-format=+1.5] S[table-format=1.3]}
\toprule
{Training groups} & {Achieved @1} & {vs.\ OptiPrime} & {vs.\ ensemble} & {$p$ vs.\ OptiPrime} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item References: OptiPrime %.5f, published unadapted ensemble %.5f. Every budget
also used 5,561 labelled validation groups. Small budgets have one seed/subsample;
the full budget has three seeds. These are not total-label learning curves.
The matched-start audit does not establish harm at 200 training groups.
\end{tablenotes}\end{threeparttable}\end{table}
""" % (op, ours))


# ----------------------------------------------------------- source retention --------
def tab_retention(e28, e27):
    _, by = collect(e27)
    s0 = e28["models"]["start_checkpoint"]
    grouped = {}
    for k, v in e28["models"].items():
        if k == "start_checkpoint":
            continue
        a, _ = arm_of(k)
        grouped.setdefault(a, []).append(v)
    rows = []
    for a in ("Z", "S", "P", "M", "shared"):
        if a not in grouped:
            continue
        g = grouped[a]
        tgt = np.mean(by[a]["delta"]) if a in by else float("nan")
        rows.append(f"{tex_arm(a)} & {len(g)} & {np.mean([x['spearman'] for x in g]):.4f} & "
                    f"{np.mean([x['spearman_change'] for x in g]):+.4f} & "
                    f"{np.mean([x['decision_change'] for x in g]):+.5f} & {tgt:+.5f} \\\\")
    w("tab_retention.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}\footnotesize
\caption{Historical E28 retention of the original prediction head only. Source fold 0, %s rows,
not used for adaptation training. The starting checkpoint scores %.4f pooled Spearman and
%.5f achieved @1 there.}
\label{tab:retention}
\begin{tabular}{l S[table-format=1] S[table-format=1.4] S[table-format=+1.4]
                  S[table-format=+1.5] S[table-format=+1.5]}
\toprule
Arm & {Seeds} & {Source $\rho$} & {Source $\rho$ change} & {Source @1 change} &
{Target gain vs.\ OptiPrime} \\
\midrule
""" % (f"{e28['surface']['rows']:,}", s0["spearman"], s0["decision_at_1"])
      + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item For S, M and Z the source metric here is NOT the deployed selector, whereas
the target gain uses that selector. Do not infer cross-library selector retention
from this table. The updated both-head audit is reported separately.
\end{tablenotes}\end{threeparttable}\end{table}
""")


# --------------------------------------------------------- seed-paired contrasts -----
def tab_paired(e27):
    vp = e27["validation_paired"]
    rows = []
    for k, d in vp.items():
        rows.append(f"{k.replace('_minus_', ' $-$ ')} & {len(d['per_seed'])} & "
                    f"{', '.join(f'{x:+.5f}' for x in d['per_seed'])} & {d['mean']:+.5f} & "
                    f"{'yes' if d['same_sign'] else NO} \\\\")
    w("tab_paired.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}\footnotesize
\caption{Historical seed-paired validation contrasts. These are descriptive model-selection
results: neither sign agreement nor disagreement establishes a mechanism or equivalence.}
\label{tab:paired}
\begin{tabular}{l S[table-format=1] l S[table-format=+1.5] c}
\toprule
Contrast & {Seeds} & {Per seed} & {Mean} & {All seeds agree} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}\end{threeparttable}\end{table}
""")


def tab_followup(e29, e30):
    rows = []
    for arm in ("P", "S", "S_pairwise", "M", "shared", "Z"):
        v = e29["source_means_by_arm"][arm]
        p, s = v["prediction"], v["selection"]
        label = arm.replace("_", ", ")
        rows.append(f"{label} & {v['n_seeds']} & {p['achieved_at_1']:.5f} & "
                    f"{s['achieved_at_1']:.5f} & {p['spearman']:.4f} & {s['spearman']:.4f} \\\\")
    start = e29["surfaces"]["source_fold0"]["start_checkpoint"]["prediction"]
    w("tab_heads.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}\small
\caption{Both outputs on source fold 0: 20,509 rows and 1,463 informative groups.
Means across available seeds, not ensembles; M, shared and Z are single-seed audits.}
\label{tab:heads}
\begin{tabular}{lr rrrr}\toprule
Arm & Seeds & Prediction @1 & Selection @1 & Prediction $\rho$ & Selection $\rho$ \\
\midrule
""" + f"Starting checkpoint & 1 & {start['achieved_at_1']:.5f} & {start['achieved_at_1']:.5f} & "
      f"{start['spearman']:.4f} & {start['spearman']:.4f} \\\\\n" + "\n".join(rows) + r"""
\bottomrule\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item Source achieved @1 uses informative groups with at least two distinct designs;
target results include all eligible groups. Absolute levels are not directly comparable.
P and shared deploy the prediction score; S, M and Z deploy the separate selection score.
\end{tablenotes}\end{threeparttable}\end{table}
""")
    rows = []
    for arm in ("P", "S", "S_pairwise", "shared"):
        values = [v["validation_achieved_at_1"] for v in e30["models"].values() if v["arm"] == arm]
        rows.append(f"{arm.replace('_', ', ')} & {len(values)} & {np.mean(values):.6f} \\\\")
    w("tab_replication.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}\small
\caption{Completed three-seed validation comparison, using selected-epoch training-log values.
The additional pairwise seeds were not evaluated on target test.}
\label{tab:replication}
\begin{tabular}{lrr}\toprule Arm & Seeds & Validation achieved @1 \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule\end{tabular}
\end{threeparttable}\end{table}
""")
    rows = []
    for reference in ("P", "S", "shared"):
        d = e29["paired_contrasts"]["target_val"][f"S_pairwise_minus_{reference}_mean_of_three_seeds"]
        lo, hi = d["ci95"]
        rows.append(f"Pairwise $-$ {reference} & {d['observed']:+.6f} & "
                    f"$[{lo:+.6f}, {hi:+.6f}]$ & {d['two_sided_p']:.3f} \\\\")
    w("tab_followup_contrasts.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}\small
\caption{Direct contrasts from cached validation predictions, averaging each group's
outcomes over three seeds before resampling whole locus components.}
\label{tab:followupcontrasts}
\begin{tabular}{lrrr}\toprule Contrast & Difference & 95\% interval & $p$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item Conditional on selected checkpoints; unadjusted development comparisons, not
independent confirmation. Re-evaluation values can differ slightly from training logs
because of numerical/batch effects. Seed means do not represent an ensemble.
\end{tablenotes}\end{threeparttable}\end{table}
""")


def main():
    e25, e27, e28 = (load("e25_adaptation_partition"), load("e27_adaptation_test"),
                     load("e28_source_retention"))
    tab_partition(e25)
    tab_test(e27)
    tab_curve(e27)
    tab_retention(e28, e27)
    tab_paired(e27)
    tab_followup(load("e29_head_audit"), load("e30_pairwise_replication"))


if __name__ == "__main__":
    main()
