"""Replace the manuscript's deployment-utility table with one tested code path.

`tables/tab_utility.tex` computes every metric "within a protospacer group" and captions
that as the deployment task. E01 measured that grouping: of the 735 protospacer groups with
five or more rows, **100% span more than one source/cell/editor condition** and 26% contain
more than one intended allele, so ranking inside one is largely a comparison of loci and
conditions rather than of interchangeable designs. It was also computed by code with four
defects (E16), of which the random baseline's tie handling changes a published number by a
third.

This emits one table with three panels, all through `endpoints.py`:

  A  the manuscript's protospacer grouping, corrected arithmetic, kept for continuity
  B  fold 0's fixed-allele decision -- the corrected estimand, at the depth fold 0 supports
  C  the reserved panel -- the same estimand at real candidate depth, on a surface neither
     model was trained on

Usage: PYTHONPATH=src .venv/bin/python explore_v2/make_utility_table.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from string import Template

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _v2common as C  # noqa: E402
import endpoints as E  # noqa: E402

OUT = C.ROOT / "reports/paper/tables"


class LT(Template):
    delimiter = "@"


TAB = LT(r"""% generated by explore_v2/make_utility_table.py -- do not edit by hand
\begin{table}[H]
\centering
\begin{threeparttable}
\caption{Deployment utility under three groupings. A user has already fixed the allele they
want and the cell and editor they work in, so the group they face is one intended allele in
one experimental context (panels B and C). Panel A is the grouping this manuscript
originally reported, retained for continuity.}
\label{tab:utility}
\footnotesize
\begin{tabular}{l S[table-format=1.4] S[table-format=1.4] S[table-format=1.4] S[table-format=+1.5] c}
\toprule
Metric & {Random} & {OptiPrime} & {PE-RankFormer} & {$\Delta$} & {95\% CI} \\
\midrule
\multicolumn{6}{l}{\emph{A. Protospacer groups (not the deployment task): @a_n groups}}\\
@a_rows
\midrule
\multicolumn{6}{l}{\emph{B. Fixed allele $\times$ context, held-out fold 0: @b_n groups}}\\
@b_rows
\midrule
\multicolumn{6}{l}{\emph{C. Fixed allele $\times$ context, reserved panel: @c_n groups}}\\
@c_rows
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item One candidate is one distinct pegRNA design in one decision context; repeated
measurements of a design are averaged before ranking. Achieved efficiency at $k$ is defined
only where at least $k$ distinct candidates exist, and each budget is scored on that
population with its own random baseline. Tied measured maxima receive full credit, so a
random pick's hit rate is the number of maximisers divided by the candidate count.
Intervals resample the dependence unit -- protospacers in A and B, target sites in C.
\item \textbf{Panel A is not the design problem, and its groups are shallower than
described.} All @a_n span more than one source/cell/editor condition and @a_multi\% contain
more than one intended allele. They were selected for carrying five or more \emph{rows}: the
median number of distinct pegRNA designs in them is @a_med_designs, and only @a_ge5
protospacers in the held-out set carry five or more distinct designs. So a ranking inside one
mixes ``which locus and condition is easy'' with ``which pegRNA is best''. Fold 0 contains
@b_n informative fixed-allele groups and \emph{none} with five candidates, which is why panel
C exists.
\item \textbf{Panels B and C disagree, and C is the one at deployment depth.} On fold 0's
binary choice PE-RankFormer is ahead. On the panel, at candidate depths up to twelve and on
a library neither model was trained on, OptiPrime obtains more efficiency from its single
nominated candidate; the gap widens with candidate depth and with how much the choice is
worth. Both models remain far ahead of random selection.
\item Reproduce with \path{explore_v2/make_utility_table.py}; endpoint invariants are tested
in \path{explore_v2/test_endpoints.py}.
\end{tablenotes}
\end{threeparttable}
\end{table}
""")

ROWS = [("Achieved efficiency of the top pick", "at_1", 4),
        ("Achieved efficiency, best of 3", "at_3", 4),
        ("Best-design hit rate", "hit", 4),
        ("Regret vs.\\ the best measured design", "regret", 5)]


def panel(t: pd.DataFrame, site: str, seed: int = 20260908) -> tuple[str, dict]:
    """LaTeX rows plus the raw numbers, for one grouping."""
    lines, raw = [], {}
    for label, key, dp in ROWS:
        cells = []
        for m in ("rand", "op", "ours"):
            col = f"{m}_{key}" if key != "regret" else f"{m}_regret"
            v = t[col].mean() if col in t else np.nan
            raw[f"{m}_{key}"] = float(v)
            cells.append("{--}" if not np.isfinite(v) else f"{v:.{dp}f}")
        a, b = f"ours_{key}", f"op_{key}"
        if a in t and b in t:
            d = E.paired_cluster_bootstrap((t[a] - t[b]).to_numpy(), t[site].to_numpy(), seed)
            raw[f"delta_{key}"] = d
            dd = f"{d['observed']:+.5f}"
            ci = f"$[{d['ci95'][0]:+.5f},\\,{d['ci95'][1]:+.5f}]$"
        else:
            dd, ci = "{--}", "{--}"
        lines.append(f"{label} & " + " & ".join(cells) + f" & {dd} & {ci} \\\\")
    return "\n".join(lines), raw


def main() -> None:
    seed = 20260908
    man = pd.read_parquet(C.require_manifest())
    pred = C.load_heldout_predictions()
    f0 = (man[man.fold == 0].merge(pred, on="record_id", validate="1:1")
          .rename(columns={"edited": "edited_frac", "op": "op_score", "ours": "ours_score"}))
    f0 = f0.rename(columns={"op_score": "op", "ours_score": "ours"})
    f0["protospacer"] = f0.spacer

    # --- panel A: the manuscript's own grouping, reproduced faithfully ------------------
    # The paper ranks ROWS within a protospacer and requires five rows, so this does the
    # same rather than aggregating designs; only the random baseline's tie arithmetic is
    # corrected. The note records what those groups actually contain.
    gs = f0.groupby("spacer", observed=True).agg(
        rows=("edited_frac", "size"), designs=("design_key", "nunique"),
        alleles=("edit_key", "nunique"), conds=("cond3", "nunique"))
    keep = set(gs.index[gs.rows >= 5])
    a_t = E.score_population(f0[f0.spacer.isin(keep)], ["ours", "op"], ks=(1, 3),
                             group="spacer")
    a_t = a_t[a_t.informative]
    a_rows, a_raw = panel(a_t, "site", seed)

    # --- panel B: fold 0's fixed-allele decision ----------------------------------------
    b_cand = E.aggregate_candidates(f0, group="decision_group", scores=("ours", "op"))
    nd = b_cand.groupby("decision_group", observed=True).design_key.transform("nunique")
    b_t = E.score_population(b_cand[nd >= 2], ["ours", "op"], ks=(1, 3),
                             group="decision_group")
    b_t = b_t[b_t.informative]
    b_rows, b_raw = panel(b_t, "site", seed)

    # --- panel C: the reserved panel ----------------------------------------------------
    c = json.loads((C.OUT / "e16_corrected_endpoints.json").read_text())["strata"][1]
    c_lines = []
    for label, key, dp in ROWS:
        k = {"at_1": "achieved_at_1", "at_3": "achieved_at_3",
             "hit": "hit_at_1", "regret": "regret_at_1"}[key]
        cells = [f"{c['arms'][m][k]:.{dp}f}" if k in c["arms"][m] else "{--}"
                 for m in ("rand", "op", "ours")]
        d = c["paired"]["ours_minus_op_at_1"] if key == "at_1" else None
        dd = f"{d['observed']:+.5f}" if d else "{--}"
        ci = (f"$[{d['ci95'][0]:+.5f},\\,{d['ci95'][1]:+.5f}]$") if d else "{--}"
        c_lines.append(f"{label} & " + " & ".join(cells) + f" & {dd} & {ci} \\\\")

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "tab_utility.tex").write_text(TAB.substitute(
        a_n=f"{len(a_t):,}", a_multi=f"{100*(gs.alleles[gs.rows>=5]>1).mean():.0f}",
        a_med_designs=f"{gs.designs[gs.rows>=5].median():.0f}",
        a_ge5=f"{int((gs.designs >= 5).sum()):,}",
        a_rows=a_rows, b_n=f"{len(b_t):,}", b_rows=b_rows,
        c_n=f"{c['groups']:,}", c_rows="\n".join(c_lines)))
    (C.OUT / "utility_table_numbers.json").write_text(json.dumps(
        {"panel_A_protospacer": a_raw, "panel_B_fold0_allele": b_raw,
         "panel_A_groups": int(len(a_t)), "panel_B_groups": int(len(b_t)),
         "panel_C_groups": int(c["groups"])}, indent=2, default=float))
    print(f"wrote {OUT/'tab_utility.tex'}")
    print(f"panel A {len(a_t):,} groups | panel B {len(b_t):,} | panel C {c['groups']:,}")
    for nm, raw in (("A", a_raw), ("B", b_raw)):
        print(f"  {nm}: ours@1={raw['ours_at_1']:.4f} op@1={raw['op_at_1']:.4f} "
              f"rand@1={raw['rand_at_1']:.4f} rand_hit={raw['rand_hit']:.4f}")


if __name__ == "__main__":
    main()
