"""Generate the LaTeX tables for reports/explore_v2_report.tex from the JSON artifacts.

Every number in the report is read out of an experiment's own JSON output, so the report
cannot drift from the data. Re-run after any experiment is re-run.

Usage: .venv/bin/python explore_v2/make_report_tables.py
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "reports" / "tables_explore_v2"
HDR = "% generated by explore_v2/make_report_tables.py -- do not edit by hand\n"
YES, NO = "yes", r"\textbf{no}"

ARM_WHAT = {"A_ens": "released recipe", "D_ens": "canonical batching, ranking on",
            "E_ens": "canonical batching, ranking off",
            "F_ens": "canonical batching, ranking on",
            "H_ens": "canonical batching, ranking off"}
FEAT_MARK = {"A_ens": "", "D_ens": "", "E_ens": "", "F_ens": r"$\dagger$",
             "H_ens": r"$\dagger$"}

LAB = {"op": "OptiPrime", "ours": "PE-RankFormer (published)",
       "Ffold": r"\textbf{Arm F, 5 per-fold}", "F_ens": "Arm F, 3 seeds",
       "F3_ens": "Arm F, 3 seeds", "A_ens": "Arm A, 3 seeds (released)",
       "D_ens": "Arm D, 3 seeds", "E_ens": "Arm E, 3 seeds", "H_ens": "Arm H, 3 seeds",
       "rand": "Random choice", "oracle": "Perfect chooser",
       "Ffold_cal": r"Arm F, 5 per-fold, calibrated"}


def load(stem):
    p = HERE / f"{stem}.json"
    return json.loads(p.read_text()) if p.exists() else None


def w(name, body):
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(HDR + body)
    print("wrote", (OUT / name).relative_to(HERE.parent))


def ci(d, f="{:+.5f}"):
    return f"$[{f.format(d['ci95'][0])},\\,{f.format(d['ci95'][1])}]$"


def pv(x):
    return r"$<$0.001" if x < 0.001 else f"{x:.3f}"


def esc(s):
    return s.replace(">=", r"$\geq$").replace("+", r"$+$")


# ------------------------------------------------------------- panel decision --------
def tab_panel(e22, e24):
    strata = e24["panel"]["strata"] if e24 else e22["strata"]
    order = ["rand", "op", "ours", "A_ens", "F3_ens" if e24 else "F_ens", "Ffold", "oracle"]
    rows = []
    for s in strata:
        rows.append(r"\midrule")
        rows.append(r"\multicolumn{5}{l}{\emph{%s --- %s groups, %s sites}}\\[1pt]"
                    % (esc(s["stratum"]), f"{s['groups']:,}", f"{s['sites']:,}"))
        for m in order:
            if m not in s["arms"]:
                continue
            a = s["arms"][m]
            if m == "oracle":
                rows.append(f"{LAB[m]} & {a['achieved_at_1']:.4f} & 1.0000 & 0.00000 & "
                            r"{--} \\")
                continue
            d = s["paired"].get(f"{m}_minus_op")
            delta = (f"${d['observed']:+.5f}$ {ci(d)}" if d else "{--}")
            rows.append(f"{LAB.get(m, m)} & {a['achieved_at_1']:.4f} & {a['hit_at_1']:.4f} "
                        f"& {a['regret_at_1']:.5f} & {delta} \\\\")
    w("tab_panel_decision.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}
\caption{The fixed-allele decision on the reserved panel. A candidate is one distinct pegRNA
design in one decision context; repeated measurements of a design are averaged before
ranking. The last column is the paired difference against OptiPrime, with a 95\% interval
from a cluster bootstrap resampling target sites.}
\label{tab:panel}\footnotesize
\begin{tabular}{l S[table-format=1.4] S[table-format=1.4] S[table-format=1.5] l}
\toprule
Model & {Achieved @1} & {Hit rate @1} & {Regret @1} & {$\Delta$ vs.\ OptiPrime} \\
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item Achieved efficiency at $k$ is defined only where at least $k$ distinct candidates
exist. Tied measured maxima receive full credit, so a random pick's hit rate is the number
of maximisers divided by the candidate count.
\end{tablenotes}\end{threeparttable}\end{table}
""")


# ------------------------------------------------------- the decisive contrast -------
def tab_headline(e24):
    if not e24:
        return
    s = next(x for x in e24["panel"]["strata"] if x["stratum"] == "all eligible groups")
    rows = []
    for k in ("Ffold_minus_ours", "Ffold_minus_F3_ens", "Ffold_minus_A_ens",
              "Ffold_minus_E_ens", "Ffold_minus_H_ens", "Ffold_minus_op",
              "ours_minus_op"):
        if k not in s["paired"]:
            continue
        a, b = k.split("_minus_")
        d = s["paired"][k]
        rows.append(f"{LAB.get(a, a)} $-$ {LAB.get(b, b)} & {d['observed']:+.5f} & "
                    f"{ci(d)} & {pv(d['two_sided_p'])} \\\\")
    d0 = e24["fold0"]["decision"]["paired"]
    for k in ("Ffold_minus_ours", "Ffold_minus_op"):
        if k not in d0:
            continue
        a, b = k.split("_minus_")
        d = d0[k]
        rows.append(r"\quad on fold 0: " + f"{LAB.get(a, a)} $-$ {LAB.get(b, b)} & "
                    f"{d['observed']:+.5f} & {ci(d)} & {pv(d['two_sided_p'])} \\\\")
    w("tab_headline.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}
\caption{Does the improved recipe beat the published model when the two are built alike?
Both are five checkpoints, one per official fold, combined by the same plain mean of
predicted efficiencies. Achieved efficiency at rank 1, all eligible panel groups.}
\label{tab:headline}\scriptsize
\begin{tabular}{l S[table-format=+1.5] l l}
\toprule
Contrast & {$\Delta$ achieved @1} & {95\% CI} & {$p$} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}\end{threeparttable}\end{table}
""")


# ------------------------------------------- does the feature branch transfer? -------
def tab_arms_panel(e22):
    """Every arm's three-seed ensemble on the panel. The fold-0 matrix says the feature
    branch helps and the ranking loss is a null; this asks whether either survives a library
    outside the development corpus."""
    s = next(x for x in e22["strata"] if x["stratum"] == "all eligible groups")
    rows = []
    for m in ("A_ens", "D_ens", "E_ens", "F_ens", "H_ens"):
        if m not in s["arms"]:
            continue
        a = s["arms"][m]
        d, o = s["paired"].get(f"{m}_minus_op"), s["paired"].get(f"{m}_minus_ours")
        rows.append(
            f"{m[0]}{FEAT_MARK[m]} & {ARM_WHAT[m]} & {a['achieved_at_1']:.4f} & "
            f"{s['pooled_spearman'].get(m, float('nan')):.4f} & "
            + (f"{d['observed']:+.5f}" if d else "{--}") + " & "
            + (f"{o['observed']:+.5f}" if o else "{--}") + " & "
            + (pv(o["two_sided_p"]) if o else "{--}") + r" \\")
    ref = [f"{LAB[m]} & & {s['arms'][m]['achieved_at_1']:.4f} & "
           f"{s['pooled_spearman'].get(m, float('nan')):.4f} & & & \\\\"
           for m in ("op", "ours")]
    w("tab_arms_panel.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}
\caption{Every training arm's three-seed ensemble on the reserved panel, all eligible groups.
Ensemble size is matched across arms, so it cannot explain a difference, and feature
standardisation is frozen to each checkpoint's training folds. Arms marked $\dagger$ carry the
Family C feature branch.}
\label{tab:armspanel}\scriptsize
\begin{tabular}{@{}ll S[table-format=1.4] S[table-format=1.4]
                    S[table-format=+1.5] S[table-format=+1.5] l@{}}
\toprule
& & & & \multicolumn{2}{c}{$\Delta$ achieved @1 vs.} & \\
\cmidrule(lr){5-6}
Arm & What it changes & {Achieved @1} & {Pooled $\rho$} & {OptiPrime} & {published} & {$p$} \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
""" + "\n".join(ref) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item The $p$ column refers to the contrast against the published member. Ten contrasts were
computed on this surface, so a nominal $p$ near 0.02 is weak evidence; and the panel is used
here for development, not confirmation.
\end{tablenotes}\end{threeparttable}\end{table}
""")


# --------------------------------------------------------------- correlations --------
def tab_corr(e21, e24):
    rows = []
    for surf, s in e21["surfaces"].items():
        rows.append(r"\midrule")
        rows.append(r"\multicolumn{4}{l}{\emph{%s --- %s rows, %s clusters}}\\[1pt]"
                    % (surf, f"{s['n_rows']:,}", f"{s['n_clusters']:,}"))
        for m, v in s["models"].items():
            rows.append(f"{m} & {v['spearman']:.4f} & {v['pearson']:.4f} & \\\\")
        for k, nm in (("spearman_raw", "Spearman"),
                      ("pearson_calibrated", "Pearson (calibrated)")):
            d = s["paired_vs_optiprime"][k]
            rows.append(r"\quad\emph{margin, %s} & \multicolumn{2}{l}{$%+.4f$} & %s\ \ %s \\"
                        % (nm, d["observed"], ci(d, "{:+.4f}"), pv(d["two_sided_p"])))
    if e24:
        for key, nm in (("fold0", "held-out fold 0"), ("panel", "reserved panel")):
            c = e24[key]["correlations"]
            rows.append(r"\midrule")
            rows.append(r"\multicolumn{4}{l}{\emph{Arm F, five per-fold checkpoints --- %s}}\\[1pt]"
                        % nm)
            for m in ("Ffold", "Ffold_cal"):
                rows.append(f"{LAB[m]} & {c[m]['spearman']:.4f} & {c[m]['pearson']:.4f} "
                            r"& \\")
            for k, lbl in (("spearman_Ffold", "Spearman"),
                           ("pearson_Ffold_calibrated", "Pearson (calibrated)")):
                d = e24[key]["margins_over_optiprime"].get(k)
                if d:
                    rows.append(
                        r"\quad\emph{margin, %s} & \multicolumn{2}{l}{$%+.4f$} & %s\ \ %s \\"
                        % (lbl, d["observed"], ci(d, "{:+.4f}"), pv(d["two_sided_p"])))
    w("tab_correlations.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}
\caption{Pooled correlation on both surfaces. Pearson is on the isotonic-calibrated scale
because the ordinal head emits rank estimates rather than efficiencies; each calibrator is
fitted on its own model's development out-of-fold predictions and applied unchanged.
Margins are against OptiPrime, with cluster-bootstrap intervals.}
\label{tab:corr}\footnotesize
\begin{tabular}{l S[table-format=1.4] S[table-format=1.4] l}
\toprule
& {Spearman} & {Pearson} & {95\% CI \quad $p$} \\
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item Intervals and $p$ values come from a 2000-resample cluster bootstrap, so
$p = 0.0005$ is the resolution floor and is reported here as $<$0.001.
\end{tablenotes}\end{threeparttable}\end{table}
""")


# ------------------------------------------------------------ ablation matrix --------
def tab_matrix(e19):
    rows = [f"{a['arm']} & {a['description']} & {a['n_seeds']} & "
            f"{a['mean_fold0_achieved']:.5f} & {a['mean_pooled_rho']:.4f} & "
            f"{a['mean_train_pairs_per_epoch']:.0f} \\\\"
            for a in sorted(e19["by_arm"], key=lambda x: x["arm"])]
    pr = []
    for k in ("F_minus_A", "E_minus_A", "H_minus_A", "D_minus_A", "F_minus_E", "H_minus_F",
              "F_minus_D", "D_minus_E", "H_minus_E", "D_minus_C", "G_minus_D", "B_minus_A",
              "D_minus_B"):
        d = e19["paired"].get(k)
        if not d:
            continue
        pr.append(f"{k.replace('_minus_', ' $-$ ')} & {len(d['per_seed'])} & "
                  f"{d['mean']:+.5f} & "
                  f"{'{--}' if len(d['per_seed']) < 2 else (YES if d['same_sign'] else NO)}"
                  r" \\")
    sc = e19["selector_comparison"]
    w("tab_matrix.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}
\caption{The decision-aligned training matrix, scored on fold 0's %s informative decision
groups. No arm trains or early-stops on fold 0.}
\label{tab:matrix}\footnotesize
\begin{tabular}{cl S[table-format=1] S[table-format=1.5] S[table-format=1.4] S[table-format=6.0]}
\toprule
Arm & What it changes & {Seeds} & {Achieved @1} & {Pooled $\rho$} & {Pairs/epoch} \\
\midrule
""" % f"{e19['surface']['informative_decision_groups']:,}" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}

\vspace{0.9em}
\begin{tabular}{l S[table-format=1] S[table-format=+1.5] l}
\toprule
Seed-paired contrast & {Seeds} & {Mean $\Delta$} & {All seeds agree in sign} \\
\midrule
""" + "\n".join(pr) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item A contrast whose seeds disagree in sign is not evidence for a mechanism however large
its mean. On that criterion the load-bearing effects here are canonical batching (E $-$ A)
and the feature branch (F $-$ E), while the ranking-pair contrast with batching held fixed
(D $-$ E) is not one of them. \textbf{Only the first of those survives an external library:}
on the reserved panel F $-$ E reverses sign to $-0.00025$ ($p = 0.006$), so three-of-three
seed agreement on the held-out fold did not make it a safe component decision
(Table~\ref{tab:armspanel}).
\item \textbf{Checkpoint selection is a null.} Selecting on the decision metric rather than
pooled $\rho$ gains %+.5f in fold-0 achieved efficiency over the same %d trajectories,
even though the two selectors choose different epochs in %d of them.
\end{tablenotes}\end{threeparttable}\end{table}
""" % (sc["mean_gain_from_decision_selection"], sc["runs"], sc["runs_where_selectors_disagree"]))


# ------------------------------------------------------------- E23 diagnostics -------
def tab_geometry(e23):
    z, b, g = (e23["interpretable_size"], e23["length_bias_of_the_nominated_design"],
               e23["global_length_correction"])
    rows = []
    for m, v in z["captured"].items():
        bb = b.get(m, {})
        rows.append(f"{LAB.get(m, m)} & {v['achieved_at_1']:.4f} & "
                    f"{v['share_of_available_gain']*100:.1f} & "
                    f"{bb.get('pbs_bias', float('nan')):+.3f} & "
                    f"{bb.get('rtt_bias', float('nan')):+.3f} \\\\")
    sw = g["rtt_sweep"]
    w("tab_geometry.tex", r"""\begin{table}[htbp]\centering\begin{threeparttable}
\caption{Where the decision is lost. On %s informative panel groups a random pick achieves
%.4f and a perfect chooser %.4f, so the whole decision is worth %.4f efficiency. Length bias
is the mean difference in PBS or RTT length between the design a model nominates and the
best-measured design.}
\label{tab:geometry}\footnotesize
\begin{tabular}{l S[table-format=1.4] S[table-format=2.1] S[table-format=+1.3] S[table-format=+1.3]}
\toprule
Model & {Achieved @1} & {\%% of gain} & {PBS bias} & {RTT bias} \\
\midrule
""" % (f"{z['informative_groups']:,}", z["random"], z["oracle"], z["decision_is_worth"])
      + "\n".join(rows) + r"""
\bottomrule
\end{tabular}

\vspace{0.9em}
\begin{tabular}{l%s}
\toprule
$\alpha$ & %s \\
\midrule
Achieved @1 & %s \\
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft]\footnotesize
\item The sweep adds $\alpha\cdot\mathrm{len(RTT)}$ to the out-of-fold score on %s
development decision groups against a baseline of %.5f. The optimum is exactly $\alpha=0$:
the length preference is not a global additive offset and cannot be removed by one.
\end{tablenotes}\end{threeparttable}\end{table}
""" % ("r" * len(sw), " & ".join(f"${k}$" for k in sw),
       " & ".join(f"{v:.5f}" for v in sw.values()),
       f"{g['informative_groups']:,}", g["baseline"]))


def main():
    e19, e21 = load("e19_matrix_results"), load("e21_correlation_surfaces")
    e22, e23 = load("e22_best_arm_on_panel"), load("e23_where_the_decision_is_lost")
    e24 = load("e24_perfold_recipe")
    tab_panel(e22, e24)
    tab_arms_panel(e22)
    tab_headline(e24)
    tab_corr(e21, e24)
    tab_matrix(e19)
    tab_geometry(e23)


if __name__ == "__main__":
    main()
