"""Check every number the Gate A report asserts against the artefact that produced it.

Same idea as `reproduce/verify_manuscript.py`: a claim written in prose and a number stored
in a JSON are two copies of one fact, and the copies drift. Each entry names the file, the
path into it, and the value the report states. Run this after editing either side.

Usage: .venv/bin/python explore_v2/verify_report.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent

# (artefact, dotted path, expected value, tolerance, what the report says)
CLAIMS = [
    ("e01_decision_manifest.json", "keys.canonical_edits", 51766, 0,
     "52,507 canonical alleles"),
    ("e01_decision_manifest.json", "keys.decision_groups", 175668, 0,
     "176,554 decision groups"),
    ("e01_decision_manifest.json", "keys.targets_with_multiple_windows_one_edit", 32181, 0,
     "32,199 sites whose several windows are one allele"),
    ("e01_decision_manifest.json", "keys.edits_reached_by_multiple_spacers", 8024, 0,
     "7,702 alleles reachable by more than one protospacer"),
    ("e01_decision_manifest.json", "availability.fold0_heldout.groups_ge_2", 2412, 0,
     "fold 0 has 2,412 groups with >=2 designs"),
    ("e01_decision_manifest.json", "availability.fold0_heldout.groups_ge_5", 0, 0,
     "fold 0 has none with >=5"),
    ("e01_decision_manifest.json", "fold_structure.by_key.spacer.frac_split", 0.807, 0.002,
     "80.7% of fold-0 protospacers also appear in training"),
    ("e01_decision_manifest.json",
     "fold_structure.fold0_rows_in_decision_group_shared_with_other_folds", 4931, 0,
     "23.8% of fold-0 rows (4,885) share a decision group with training"),

    ("e02_corrected_metrics.json", "grouping_ladder.0.ours", 0.6357, 0.0002,
     "spacer grouping: ensemble 0.6357"),
    ("e02_corrected_metrics.json", "grouping_ladder.0.op", 0.5471, 0.0002,
     "spacer grouping: OptiPrime 0.5471"),
    ("e02_corrected_metrics.json", "grouping_ladder.3.delta_ours_op", 0.1735, 0.0005,
     "allele x context >=2: +0.1735"),
    ("e02_corrected_metrics.json", "pairwise.scorable_groups", 1390, 0,
     "1,390 scorable binary choices"),
    ("e02_corrected_metrics.json", "pairwise.metrics.ours.accuracy", 0.747, 0.001,
     "ensemble accuracy 0.747"),
    ("e02_corrected_metrics.json", "pairwise.metrics.ordssm.accuracy", 0.750, 0.001,
     "ordinal-S4D accuracy 0.750"),
    ("e02_corrected_metrics.json", "pairwise.metrics.op.accuracy", 0.657, 0.001,
     "OptiPrime accuracy 0.657"),
    ("e02_corrected_metrics.json", "pairwise.metrics.ours.regret", 0.0065, 0.0002,
     "ensemble regret 0.0065"),
    ("e02_corrected_metrics.json", "pairwise.metrics.random.regret", 0.0316, 0.0002,
     "random regret 0.0316"),

    ("e03_matched_support.json", "support.n_quartets", 111862, 0, "110,321 quartets"),
    ("e03_matched_support.json", "noise_model.sigma_z", 0.0378, 0.0002,
     "per-measurement SD 0.0378 on the arcsine scale"),
    ("e03_matched_support.json",
     "variance_components.interaction_share_of_delta_variance", 0.288, 0.002,
     "interaction is 28.5% of the design-contrast variance"),
    ("e03_matched_support.json",
     "variance_components.sd_design_main_effect_estimate", 0.1890, 0.0005,
     "design main effect SD 0.1907"),
    ("e03_matched_support.json", "reversals.reversal_rate_supported", 0.0409, 0.0005,
     "supported reversal rate 4.2%"),
    ("e03_matched_support.json",
     "transfer_regret.supported_quartets.transfer_regret", 0.0070, 0.0002,
     "transfer regret 0.0073"),
    ("e03_matched_support.json",
     "transfer_regret.supported_quartets.share_of_random_regret_removed_by_transfer",
     0.925, 0.002, "context-blind transfer already removes 92.2% of random regret"),

    # E04's own numbers still verify against E04's artefact; the Gate A report now quotes
    # E09's clean figures instead, and CORRECTIONS.md C1 records why.
    ("e04_interaction_predictability.json",
     "arms.embedding_x_context.r2_vs_predict_zero", 0.392, 0.002,
     "superseded E04 value, quoted in CORRECTIONS.md C1 as the inflated one"),
    ("e04_interaction_predictability.json",
     "arms.feature_x_context_SHUFFLED_context.r2_vs_predict_zero", 0.0117, 0.002,
     "permuted context: +0.012"),
    ("e04_interaction_predictability.json",
     "arms.design_features_only.r2_vs_predict_zero", 0.0028, 0.002,
     "design features with no context: +0.003"),
    ("e04_interaction_predictability.json",
     "arms.embedding_x_context.sign_accuracy_stratified.sign_acc_by_pred_top_5pct",
     0.938, 0.002, "sign accuracy 0.941 on the top 5% by predicted magnitude"),

    ("e07_context_correction.json", "overall.base.accuracy", 0.6702, 0.0005,
     "frozen base 0.6702"),
    ("e07_context_correction.json", "paired.design_x_context.d_accuracy", 0.0023, 0.0003,
     "design x context +0.0023"),
    ("e07_context_correction.json",
     "paired.design_x_context_SHUFFLED.d_accuracy", 0.0019, 0.0003,
     "shuffled control +0.0019"),
    ("e07_context_correction.json", "paired.design_only.d_accuracy", 0.0016, 0.0003,
     "context-free correction +0.0016"),

    ("e09_clean_interaction_retest.json", "design.quartets_all_four_measurements_in_one_fold",
     47470, 0, "47,609 quartets lie entirely inside one official fold"),
    ("e09_clean_interaction_retest.json", "pooled.embedding_x_context.mean_r2", 0.1838,
     0.0005, "clean embedding x context R^2 +0.192"),
    ("e09_clean_interaction_retest.json", "pooled.embedding_x_context.min_r2", -0.0558,
     0.0005, "negative on one of five folds"),
    ("e09_clean_interaction_retest.json",
     "pooled.SHUFFLED_context_same_features.mean_r2", 0.0772, 0.0005,
     "representation-matched shuffle is +0.078, not +0.012"),
    ("e09_clean_interaction_retest.json", "pooled.embedding_design_only.mean_r2", 0.0663,
     0.0005, "same features with no context term at all: +0.069"),
    ("e09_clean_interaction_retest.json", "per_fold.1.tasks.sign_of_D_top_5pct", 0.8383,
     0.002, "sign of D on the top 5%: 0.873 on fold 1, 0.71-0.91 across folds"),
    ("e09_clean_interaction_retest.json", "per_fold.1.tasks.reversal_rate_in_top_5pct",
     0.0234, 0.002, "the top-5% stratum contains almost no order reversals"),

    ("e05_reference_panel.json", "summary.paired_vs_base.0.d_accuracy", 0.0, 0.0,
     "intercept-only adaptation changes nothing, exactly"),
    ("e05_reference_panel.json", "summary.paired_vs_base.4.d_accuracy", 0.0, 0.0,
     "intercept still exactly zero at the largest budget"),
    ("e05_reference_panel.json", "summary.paired_vs_base.5.d_accuracy", -0.0068, 0.0002,
     "affine costs -0.0068 at B=12, where a fitted slope came out negative"),
    ("e05_reference_panel.json", "summary.paired_vs_base.9.d_accuracy", 0.0, 0.0,
     "affine exactly zero at the largest budget"),
    ("e05_reference_panel.json", "summary.paired_vs_base.20.d_accuracy", -0.0186, 0.0003,
     "raw-representation residual ridge -0.0186 at B=12"),
    ("e05_reference_panel.json", "summary.paired_vs_base.24.d_accuracy", -0.0258, 0.0003,
     "raw-representation residual ridge -0.0258 at B=192"),
    ("e05_reference_panel.json", "summary.paired_vs_base.45.d_accuracy", -0.0035, 0.0003,
     "within-subspace ridge -0.0035 at B=12"),
    ("e05_reference_panel.json", "summary.paired_vs_base.49.d_accuracy", -0.0255, 0.0003,
     "within-subspace ridge -0.0255 at B=192"),
    ("e05_reference_panel.json", "summary.paired_vs_base.50.d_accuracy", -0.0024, 0.0003,
     "shuffled-label twin -0.0024 at B=12"),
    ("e05_reference_panel.json", "summary.paired_vs_base.54.d_accuracy", -0.0058, 0.0003,
     "shuffled-label twin -0.0058 at B=192"),

    # E06 surveys eligibility with a coarse design key; E10 is the authoritative panel
    # builder (exact design sequences, validated reconstruction), so panel counts are
    # verified against E10.
    ("e10_build_reserved_panel.json", "panel.groups_ge_2", 30475, 0,
     "30,475 decision groups with >=2 candidates on the reserved panel"),
    ("e10_build_reserved_panel.json", "panel.groups_ge_5", 8775, 0,
     "8,775 with >=5 candidates"),
    ("e10_build_reserved_panel.json",
     "validation_on_corpus_overlap.pbs_agrees", 1.0, 0.0001,
     "reconstructed PBS agrees with the corpus on 100% of matched rows"),
    ("e10_build_reserved_panel.json",
     "validation_on_corpus_overlap.rtt_agrees", 0.9968, 0.0005,
     "reconstructed RTT agrees on 99.68%"),

    ("e08_pilot_power.json", "paired_between_method.sd_difference", 0.0497, 0.0005,
     "measured paired SD 0.0497"),

    ("e10_build_reserved_panel.json", "reconstruction.rows_reconstructed", 288730, 0,
     "288,730 of 288,793 panel rows reconstructed"),
    ("e10_build_reserved_panel.json", "panel.rows", 118187, 0, "118,187 panel rows"),
    ("e10_build_reserved_panel.json", "panel.decision_groups", 30475, 0,
     "30,475 decision groups"),
    ("e10_build_reserved_panel.json", "panel.groups_ge_3", 18660, 0, "18,660 at depth >=3"),
    ("e10_build_reserved_panel.json", "panel.groups_ge_8", 2400, 0, "2,400 at depth >=8"),
    ("e10_build_reserved_panel.json", "panel.groups_informative", 24668, 0,
     "24,668 informative groups"),
    ("e10_build_reserved_panel.json", "panel.groups_all_zero", 5807, 0,
     "5,807 groups where every design measures exactly zero"),
    ("e10_build_reserved_panel.json", "panel.mean_best_design", 0.0461, 0.0002,
     "oracle achieves 0.0461 on the panel"),

    ("e11_score_reserved_panel.json", "pooled_spearman_sanity_check.ours", 0.7091, 0.0005,
     "pooled Spearman on the panel is 0.709"),
    ("e11_score_reserved_panel.json", "strata.0.groups", 30475, 0,
     "primary stratum is all 30,475 eligible groups"),

    # E16 supersedes E11/E15's inline endpoints; these are the values the reports quote.
    ("e16_corrected_endpoints.json", "accounting.rows_collapsed", 13, 0,
     "13 duplicate-design rows collapsed by the corrected candidate accounting"),
    ("e16_corrected_endpoints.json", "accounting.groups_dropped_by_recount", 0, 0,
     "no decision group is lost to the recount"),
    ("e16_corrected_endpoints.json", "strata.0.arms.rand.hit_at_1", 0.4442, 0.0005,
     "the corrected random hit rate is 0.4442, not 0.3354"),
    ("e16_corrected_endpoints.json", "strata.0.arms.op.achieved_at_1", 0.0369, 0.0002,
     "OptiPrime 0.0369 achieved efficiency at k=1, corrected"),
    ("e16_corrected_endpoints.json", "strata.0.arms.ours.achieved_at_1", 0.0363, 0.0002,
     "PE-RankFormer 0.0363, corrected"),
    ("e16_corrected_endpoints.json",
     "strata.0.paired.ours_minus_op_at_1.observed", -0.00064, 0.00003,
     "ours - OptiPrime is -0.00064 under the corrected accounting"),
    ("e16_corrected_endpoints.json",
     "strata.0.paired.e13_canon_minus_e13_ctrl_at_1.observed", 0.00184, 0.00003,
     "canonical - control is +0.00184"),
    ("e16_corrected_endpoints.json",
     "strata.0.paired.e13_canon_minus_op_at_1.observed", -0.00126, 0.00003,
     "the repaired arm still trails OptiPrime by 0.00126"),
    ("e16_corrected_endpoints.json",
     "strata.0.paired.ours_minus_ours_at_1.two_sided_p", 1.0, 0.0,
     "a predictor against itself now returns p = 1, not the bootstrap floor"),
    ("e16_corrected_endpoints.json",
     "strata.0.paired.ours_minus_ours_at_1.degenerate_zero_difference", True, 0,
     "and is flagged as a degenerate zero difference"),

    # The training runs report their own sampled-pair count per epoch, which matches E17a's
    # offline replay exactly: arm A 15,695 and arm D 62,028. That is an independent check on
    # the replay's methodology, not a restatement of it.
    ("e17_exposure_replay.json",
     "replays.current ranking key.sampled_pair_instances_per_epoch", 15695, 0,
     "arm A's live training log reports pairs=15695, matching the replay"),
    ("e17_exposure_replay.json",
     "replays.canonical decision group.sampled_pair_instances_per_epoch", 62028, 0,
     "arm D's live training log reports pairs=62028, matching the replay"),

    # E19's arm matrix: the repair replicates, but not through the ranking loss.
    ("e19_matrix_results.json", "surface.informative_decision_groups", 1463, 0,
     "the matrix is evaluated on fold 0's 1,463 informative decision groups"),
    ("e19_matrix_results.json", "paired.D_minus_A.mean", 0.00093, 0.00003,
     "D - A = +0.00093, the repair replicates"),
    ("e19_matrix_results.json", "paired.D_minus_A.same_sign", True, 0,
     "and does so with the same sign in all three seeds"),
    ("e19_matrix_results.json", "paired.D_minus_E.mean", -0.00006, 0.00003,
     "with batching held fixed, ranking on vs off makes no reliable difference"),
    ("e19_matrix_results.json", "paired.G_minus_D.mean", -0.00098, 0.00003,
     "and raising the pair budget to sixteen is worse"),
    ("e19_matrix_results.json", "paired.F_minus_D.mean", 0.00071, 0.00003,
     "the feature branch adds on top of canonical batching (sign-unstable across seeds)"),
    ("e19_matrix_results.json",
     "selector_comparison.mean_gain_from_decision_selection", 0.00005, 0.00003,
     "decision-metric checkpoint selection is worth +0.00005: a null"),
    ("e19_matrix_results.json", "selector_comparison.runs_where_selectors_disagree", 16, 0,
     "even though the two selectors pick different epochs in 16 of 18 runs"),

    # The headline correlation claims, on both surfaces. Fold 0 reproduces the paper's own
    # published interval independently; the panel shows the claim replicates out of sample.
    ("e21_correlation_surfaces.json",
     "surfaces.held-out fold 0.models.OptiPrime.spearman", 0.8690, 0.0002,
     "OptiPrime's headline Spearman 0.8690"),
    ("e21_correlation_surfaces.json",
     "surfaces.held-out fold 0.models.PE-RankFormer, raw score.spearman", 0.9079, 0.0002,
     "PE-RankFormer's headline Spearman 0.9079"),
    ("e21_correlation_surfaces.json",
     "surfaces.held-out fold 0.paired_vs_optiprime.spearman_raw.observed", 0.0389, 0.0002,
     "fold-0 Spearman margin +0.0389, reproducing the paper"),
    ("e21_correlation_surfaces.json",
     "surfaces.reserved panel.models.PE-RankFormer, raw score.spearman", 0.7091, 0.0005,
     "on the panel PE-RankFormer reaches Spearman 0.7091"),
    ("e21_correlation_surfaces.json",
     "surfaces.reserved panel.models.OptiPrime.spearman", 0.6931, 0.0005,
     "against OptiPrime's 0.6931"),
    ("e21_correlation_surfaces.json",
     "surfaces.reserved panel.paired_vs_optiprime.spearman_raw.observed", 0.0159, 0.0005,
     "panel Spearman margin +0.0159, so the headline claim replicates out of sample"),
    ("e21_correlation_surfaces.json",
     "surfaces.reserved panel.paired_vs_optiprime.pearson_calibrated.observed", 0.0163,
     0.0005, "and the calibrated-Pearson margin +0.0163 agrees with it"),
    ("e21_correlation_surfaces.json", "calibrator_transfer.gain", 0.0495, 0.0010,
     "the frozen isotonic map lifts panel Pearson by +0.0495 on a library it never saw"),

    ("e20_row_vs_design_accounting.json", "fold0_protospacers_with_5plus_rows", 735, 0,
     "the manuscript's 735 groups are groups of five or more ROWS"),
    ("e20_row_vs_design_accounting.json",
     "fold0_protospacers_with_5plus_distinct_designs", 146, 0,
     "only 146 held-out protospacers carry five or more distinct designs"),
    ("e20_row_vs_design_accounting.json",
     "median_distinct_designs_in_the_5plus_row_groups", 2.0, 0.01,
     "the median distinct-design count in those groups is 2, not 5"),

    ("e18_head_on_panel.json", "strata.0.groups", 30475, 0,
     "the head comparison runs on 30,475 panel groups, not fold 0's 546"),
    ("e18_head_on_panel.json",
     "strata.0.paired.ssm_minus_ordSSM.observed", -0.00026, 0.00003,
     "simplex minus ordinal is -0.00026 on the decision: the ordinal head is better"),
    ("e18_head_on_panel.json",
     "strata.0.paired.ssm_minus_ordSSM.two_sided_p", 0.009, 0.002,
     "p = 0.009, where fold 0 gave p = 0.50"),
    ("e18_head_on_panel.json",
     "strata.3.paired.ssm_minus_ordSSM.observed", -0.00123, 0.00003,
     "-0.00123 where the decision is worth >= 0.05"),
    ("e18_head_on_panel.json", "strata.0.pooled_spearman.ssm", 0.7126, 0.0005,
     "but pooled Spearman prefers the simplex head, 0.7126"),
    ("e18_head_on_panel.json", "strata.0.pooled_spearman.ordSSM", 0.7091, 0.0005,
     "against the ordinal head's 0.7091 -- the metrics disagree in sign"),

    ("e17_exposure_replay.json",
     "replays.current ranking key.sampled_pair_instances_per_epoch", 15695, 0,
     "15,695 sampled pair instances per epoch under the current key"),
    # The training runs report their own sampled-pair count per epoch, which matches E17a's
    # offline replay exactly: arm A 15,695 and arm D 62,028. That is an independent check on
    # the replay's methodology, not a restatement of it.
    ("e17_exposure_replay.json",
     "replays.canonical decision group.sampled_pair_instances_per_epoch", 62028, 0,
     "62,028 under the canonical key, a factor of 3.95 not 25.8"),
    # The training runs report their own sampled-pair count per epoch, which matches E17a's
    # offline replay exactly: arm A 15,695 and arm D 62,028. That is an independent check on
    # the replay's methodology, not a restatement of it.
    ("e17_exposure_replay.json",
     "replays.current ranking key.share_of_sampled_pairs_with_equal_rtt_length", 1.0, 0.0001,
     "100.0% of the current key's sampled pairs compare equal RTT lengths"),
    # The training runs report their own sampled-pair count per epoch, which matches E17a's
    # offline replay exactly: arm A 15,695 and arm D 62,028. That is an independent check on
    # the replay's methodology, not a restatement of it.
    ("e17_exposure_replay.json",
     "replays.canonical decision group.share_of_sampled_pairs_with_equal_rtt_length",
     0.0677, 0.0005, "6.8% under the canonical key"),
    # The training runs report their own sampled-pair count per epoch, which matches E17a's
    # offline replay exactly: arm A 15,695 and arm D 62,028. That is an independent check on
    # the replay's methodology, not a restatement of it.
    ("e17_exposure_replay.json",
     "replays.current ranking key.share_of_groups_updated", 0.0325, 0.0005,
     "3.2% of training groups receive any ranking update under the current key"),
    # The training runs report their own sampled-pair count per epoch, which matches E17a's
    # offline replay exactly: arm A 15,695 and arm D 62,028. That is an independent check on
    # the replay's methodology, not a restatement of it.
    ("e17_exposure_replay.json",
     "replays.canonical decision group.share_of_groups_updated", 0.1906, 0.0005,
     "19.1% under the canonical key"),
    ("e11_score_reserved_panel.json", "strata.0.sites", 22931, 0, "22,931 target sites"),
    ("e11_score_reserved_panel.json",
     "strata.0.arms.ours.achieved_efficiency_at_1", 0.0363, 0.0002,
     "PE-RankFormer achieves 0.0363 with one nominated candidate"),
    ("e11_score_reserved_panel.json",
     "strata.0.arms.rand.achieved_efficiency_at_1", 0.0217, 0.0002,
     "random achieves 0.0217"),
    ("e11_score_reserved_panel.json", "strata.0.arms.ours.best_design_hit_rate", 0.6599,
     0.0005, "best-design hit rate 0.6599"),
    ("e11_score_reserved_panel.json", "strata.0.arms.ours.regret_at_1", 0.00985, 0.0002,
     "regret 0.00985 against random's 0.02443"),
    ("e11_score_reserved_panel.json", "screening_effort.groups", 2400, 0,
     "screening-effort curve on 2,400 groups at depth >=8"),
    ("e11_score_reserved_panel.json",
     "screening_effort.random_candidates_to_match_ours_top1", 4, 0,
     "random needs four candidates to match the model's first pick"),
    ("e11_score_reserved_panel.json", "pooled_spearman_sanity_check.op", 0.6931, 0.0005,
     "OptiPrime's pooled Spearman on the panel is 0.693, below PE-RankFormer's 0.709"),
    ("e11_score_reserved_panel.json",
     "strata.0.arms.op.achieved_efficiency_at_1", 0.0369, 0.0002,
     "OptiPrime achieves 0.0369 with one nominated candidate, above ours"),
    ("e11_score_reserved_panel.json", "strata.0.arms.op.best_design_hit_rate", 0.6647,
     0.0005, "OptiPrime's best-design hit rate 0.6647"),
    ("e11_score_reserved_panel.json",
     "strata.0.paired_ours_minus_op.achieved_efficiency_at_1.observed", -0.00062, 0.00003,
     "ours minus OptiPrime is -0.00062 in achieved efficiency at k=1"),
    ("e11_score_reserved_panel.json",
     "strata.0.paired_ours_minus_op.achieved_efficiency_at_1.two_sided_p", 0.0005, 0.0002,
     "p = 0.0005 on that difference"),
    ("e11_score_reserved_panel.json",
     "strata.0.paired_ours_minus_op.achieved_efficiency_at_3.two_sided_p", 0.674, 0.01,
     "at a three-candidate budget the two are indistinguishable, p = 0.67"),
    ("e11_score_reserved_panel.json",
     "screening_effort.optiprime_candidates_to_match_ours_top1", 1, 0,
     "OptiPrime's single pick already matches ours"),

    ("e12_context_sensitivity.json", "n_groups_scored", 24668, 0,
     "context sensitivity measured on 24,668 informative groups"),
    ("e12_context_sensitivity.json", "variants.0.achieved_efficiency_at_1", 0.0448, 0.0002,
     "assigned context achieves 0.0448 on informative groups"),
    ("e12_context_sensitivity.json", "variants.3.achieved_efficiency_at_1", 0.0453, 0.0002,
     "a K562 assignment gives 0.0453 -- the assignment is not load-bearing"),

    ("e14_eval_regroup.json", "decision.canonical decision-group key.achieved_efficiency",
     0.1356, 0.0002, "regrouped arm achieves 0.1356 on fold 0's decision"),
    ("e14_eval_regroup.json", "decision.control (current ranking key).achieved_efficiency",
     0.1330, 0.0002, "control achieves 0.1330"),
    ("e14_eval_regroup.json", "paired_canon_minus_control.sel.observed", 0.00258, 0.00003,
     "+0.00258 achieved efficiency on fold 0"),
    ("e14_eval_regroup.json", "paired_canon_minus_control.sel.two_sided_p", 0.01, 0.002,
     "p = 0.01 on fold 0"),

    ("e15_regroup_on_panel.json",
     "strata.0.paired.e13_canon_minus_e13_ctrl.achieved_efficiency_at_1.observed",
     0.00178, 0.00003, "+0.00178 on the panel, all groups"),
    ("e15_regroup_on_panel.json",
     "strata.2.paired.e13_canon_minus_e13_ctrl.achieved_efficiency_at_1.observed",
     0.00521, 0.00003, "+0.00521 at panel depth 8+"),
    ("e15_regroup_on_panel.json",
     "strata.0.paired.e13_canon_minus_op.achieved_efficiency_at_1.observed",
     -0.00117, 0.00003, "the repaired model still trails OptiPrime by 0.00117"),
    ("e15_regroup_on_panel.json",
     "strata.0.paired.e13_ctrl_minus_op.achieved_efficiency_at_1.observed",
     -0.00295, 0.00003, "the control trails OptiPrime by 0.00295, so ~60% is recovered"),
    ("e08_pilot_power.json", "measurement_error.sigma_raw_efficiency", 0.0265, 0.0005,
     "per-measurement SD 0.0265 raw"),

    # ---- claims the LaTeX report makes about the grouping (reports/explore_v2_report.tex) --
    ("e02_corrected_metrics.json", "spacer_group_composition.frac_multi_condition", 1.0, 0,
     "all 670 protospacer groups span more than one condition"),
    ("e02_corrected_metrics.json", "spacer_group_composition.frac_multi_allele", 0.2558,
     0.0005, "26% of protospacer groups contain more than one intended allele"),
    ("e20_row_vs_design_accounting.json",
     "median_distinct_designs_in_the_5plus_row_groups", 2.0, 0,
     "median distinct designs in the >=5-row groups is 2"),
    ("e20_row_vs_design_accounting.json",
     "fold0_protospacers_with_5plus_distinct_designs", 146, 0,
     "only 146 fold-0 protospacers carry >=5 distinct designs"),
    ("e01_decision_manifest.json", "availability.fold0_heldout.spacer_groups_ge_5", 735, 0,
     "the 735 'targets with five or more designs' are groups of five or more rows"),

    # ---- E18: the metric reversal reproduces between two published members ------------
    ("e18_head_on_panel.json", "strata.0.paired.ssm_minus_ordSSM.observed", -0.00026,
     0.00001, "the ordinal head wins the decision by 0.00026"),
    ("e18_head_on_panel.json", "strata.0.paired.ssm_minus_ordSSM.two_sided_p", 0.009, 0.0005,
     "p = 0.009 for the head comparison on the decision"),
    ("e18_head_on_panel.json", "strata.0.pooled_spearman.ssm", 0.7126, 0.0001,
     "pooled rho prefers the simplex head, 0.7126"),
    ("e18_head_on_panel.json", "strata.0.pooled_spearman.ordSSM", 0.7091, 0.0001,
     "against the ordinal head's 0.7091"),

    # ---- E22: the improved recipe on the panel, with FROZEN feature standardisation ----
    ("e22_best_arm_on_panel.json", "strata.0.paired.F_ens_minus_A_ens.observed", 0.00115,
     0.00002, "arm F beats its matched control by +0.00115 on the panel"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.F_ens_minus_ours.observed", -0.00019,
     0.00002, "arm F falls slightly behind the published member, -0.00019"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.F_ens_minus_ours.two_sided_p", 0.044,
     0.001, "p = 0.044 for arm F minus the published member"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.F_ens_minus_op.observed", -0.00083,
     0.00002, "arm F still trails OptiPrime by 0.00083"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.ours_minus_op.observed", -0.00064,
     0.00002, "the published member trails OptiPrime by 0.00064"),

    # ---- E22 arms: which parts of the recipe survive an external library --------------
    ("e22_best_arm_on_panel.json", "strata.0.paired.E_ens_minus_A_ens.observed", 0.00141,
     0.00002, "canonical batching alone is worth +0.00141 on the panel"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.F_ens_minus_E_ens.observed", -0.00025,
     0.00002, "F - E reverses sign on the panel, -0.00025"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.F_ens_minus_E_ens.two_sided_p", 0.006,
     0.0005, "p = 0.006 for the reversed F - E contrast"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.H_ens_minus_E_ens.observed", 0.00018,
     0.00002, "the feature branch alone is +0.00018, not significant"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.H_ens_minus_E_ens.two_sided_p", 0.068,
     0.002, "p = 0.068 for the feature branch in isolation"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.H_ens_minus_ours.observed", 0.00024,
     0.00002, "arm H beats the published member by +0.00024"),
    ("e22_best_arm_on_panel.json", "strata.0.paired.H_ens_minus_ours.two_sided_p", 0.020,
     0.002, "nominally p = 0.020, one of ten contrasts"),
    ("e22_best_arm_on_panel.json", "strata.0.pooled_spearman.H_ens", 0.7113, 0.0001,
     "arm H reaches pooled rho 0.7113"),
    ("e22_best_arm_on_panel.json", "strata.0.pooled_spearman.E_ens", 0.7070, 0.0001,
     "arm E reaches 0.7070 with no ranking loss and no features"),
    ("e19_matrix_results.json", "paired.F_minus_E.mean", 0.00064, 0.00002,
     "F - E was +0.00064 on fold 0, the opposite sign to the panel"),
    ("e19_matrix_results.json", "paired.F_minus_E.same_sign", True, 0,
     "and all three fold-0 seeds agreed on that sign"),
    ("e19_matrix_results.json", "paired.H_minus_F.mean", -0.00050, 0.00002,
     "H - F was -0.00050 on fold 0, also the opposite sign to the panel"),
    ("e19_matrix_results.json", "paired.H_minus_F.same_sign", True, 0,
     "and all three fold-0 seeds agreed on that sign too"),

    # ---- E23: sizing the deficit, and the failed length correction --------------------
    ("e23_where_the_decision_is_lost.json", "interpretable_size.informative_groups", 24668,
     0, "24,668 informative panel groups"),
    ("e23_where_the_decision_is_lost.json", "interpretable_size.decision_is_worth", 0.0302,
     0.0001, "the whole decision is worth 0.0302 efficiency"),
    ("e23_where_the_decision_is_lost.json",
     "interpretable_size.gap_as_share_of_available_gain", 0.026, 0.002,
     "the gap is 2.6% of the available gain"),
    ("e23_where_the_decision_is_lost.json",
     "length_bias_of_the_nominated_design.op.rtt_bias", -0.531, 0.002,
     "OptiPrime is the only model preferring a shorter RTT"),
    ("e23_where_the_decision_is_lost.json",
     "length_bias_of_the_nominated_design.ours.rtt_bias", 0.162, 0.002,
     "the published member prefers a longer RTT"),
    ("e23_where_the_decision_is_lost.json", "global_length_correction.best_rtt_alpha",
     "+0.000", 0, "the optimal global RTT length coefficient is exactly zero"),
    ("e23_where_the_decision_is_lost.json", "global_length_correction.best_gain", 0.0, 1e-9,
     "a global length correction buys nothing"),
    ("e23_where_the_decision_is_lost.json", "global_length_correction.informative_groups",
     43425, 0, "swept on 43,425 development decision groups"),

    # ---- E23: the two models are complementary ---------------------------------------
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.achieved_at_1.blend", 0.0461, 0.0001,
     "an equal-weight rank average achieves 0.0461, above both models"),
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.paired.blend_minus_op.observed", 0.00055, 0.00002,
     "the blend beats OptiPrime by +0.00055"),
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.paired.blend_minus_op.two_sided_p", 0.001, 0.0005,
     "p < 0.001 for the blend over OptiPrime"),
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.paired.blend_minus_ours.observed", 0.00133, 0.00002,
     "the blend beats the published member by +0.00133"),
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.share_of_available_gain", 0.641, 0.002,
     "the blend captures 64.1% of the available gain"),
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.weight_sweep.best_weight", "0.5", 0,
     "the equal-weight choice is the sweep optimum, not cherry-picked"),
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.fold0_replication.paired.blend_minus_ours.observed",
     -0.00486, 0.00005,
     "on fold 0 the blend LOSES to PE-RankFormer alone by 0.00486"),
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.fold0_replication.paired.blend_minus_op.observed",
     0.00429, 0.00005, "though it still beats OptiPrime there by +0.00429"),
    ("e23_where_the_decision_is_lost.json",
     "blending_the_two_models.fold0_replication.achieved_at_1.ours", 0.13636, 0.0001,
     "PE-RankFormer leads OptiPrime widely on fold 0, which is why blending dilutes it"),
    # ---- E24: the recipe built the way the published model is built ------------------
    ("e24_perfold_recipe.json", "panel.strata.0.paired.Ffold_minus_ours.observed", -0.00017,
     0.00002, "per-fold arm F does not beat the published model, -0.00017"),
    ("e24_perfold_recipe.json", "panel.strata.0.paired.Ffold_minus_ours.two_sided_p", 0.062,
     0.002, "with p = 0.062 and an interval spanning zero"),
    ("e24_perfold_recipe.json", "panel.strata.0.paired.Ffold_minus_F3_ens.observed", 0.00002,
     0.00002, "per-fold construction adds nothing over three same-data seeds"),
    ("e24_perfold_recipe.json", "panel.strata.0.paired.Ffold_minus_F3_ens.two_sided_p",
     0.812, 0.005, "p = 0.81 for the ensemble-construction contrast"),
    ("e24_perfold_recipe.json", "panel.strata.0.paired.Ffold_minus_A_ens.observed", 0.00117,
     0.00002, "arm F still beats our reconstruction of the released recipe by +0.00117"),
    ("e24_perfold_recipe.json", "panel.strata.0.paired.Ffold_minus_op.observed", -0.00081,
     0.00002, "and remains behind OptiPrime by 0.00081"),
    ("e24_perfold_recipe.json", "panel.correlations.Ffold.spearman", 0.7096, 0.0001,
     "pooled rho 0.7096 against the published member's 0.7091"),
    ("e24_perfold_recipe.json", "fold0.decision.paired.Ffold_minus_ours.observed", 0.00007,
     0.00002, "on fold 0 the two are level, +0.00007"),
    ("e24_perfold_recipe.json", "fold0.decision.paired.Ffold_minus_ours.two_sided_p", 0.952,
     0.005, "p = 0.95 on fold 0"),
    ("e24_perfold_recipe.json", "fold0.correlations.Ffold.spearman", 0.9084, 0.0001,
     "fold-0 pooled rho 0.9084 against 0.9079"),
    ("e22_best_arm_on_panel.json", "strata.0.arms.A_ens.achieved_at_1", 0.0349, 0.0001,
     "arm A scores 0.0349, well below the published member's 0.0363"),
    # ---- E25-E28: target-library adaptation (ADAPTATION_SELECTION_PLAN.md) -----------
    ("e25_adaptation_partition.json", "graph.components", 20276, 0,
     "20,276 locus components in the allele-protospacer graph"),
    ("e25_adaptation_partition.json",
     "graph.alleles_reached_by_multiple_protospacers", 13803, 0,
     "13,803 alleles are reachable by more than one protospacer"),
    ("e25_adaptation_partition.json", "splits.test.groups", 5557, 0,
     "5,557 test decision groups"),
    ("e27_adaptation_test.json", "strata.0.arms.op.achieved_at_1", 0.04020, 0.00002,
     "OptiPrime achieves 0.04020 on the test components"),
    ("e27_adaptation_test.json", "strata.0.arms.ours.achieved_at_1", 0.03952, 0.00002,
     "the unadapted published model achieves 0.03952 there"),
    ("e27_adaptation_test.json", "strata.0.paired.ours_minus_op.observed", -0.00068,
     0.00002, "and still loses to OptiPrime by 0.00068 on this subset"),
    ("e27_adaptation_test.json", "strata.0.arms.P_s20260910.achieved_at_1", 0.04182,
     0.00002, "ordinary fine-tuning reaches 0.04182 on seed 1"),
    ("e27_adaptation_test.json", "strata.0.paired.P_s20260910_minus_op.observed", 0.00162,
     0.00002, "beating OptiPrime by +0.00162 on that seed"),
    ("e27_adaptation_test.json", "strata.0.paired.P_s20260910_minus_op.two_sided_p", 0.001,
     0.0005, "at p = 0.001"),
    ("e27_adaptation_test.json", "strata.0.arms.rand.achieved_at_1", 0.02323, 0.00002,
     "random choice achieves 0.02323 on the test components"),
    ("e27_adaptation_test.json", "strata.0.arms.oracle.achieved_at_1", 0.05028, 0.00002,
     "and a perfect chooser 0.05028"),
    ("e27_adaptation_test.json", "pooled_spearman.P_s20260910", 0.7773, 0.0001,
     "ordinary fine-tuning also lifts pooled rho to 0.7773"),
    ("e27_adaptation_test.json", "pooled_spearman.ours", 0.7102, 0.0001,
     "from the unadapted model's 0.7102"),
    ("e27_adaptation_test.json", "validation_paired.M_minus_P.same_sign", False, 0,
     "M does not reliably improve on P: the seeds disagree in sign"),
    ("e27_adaptation_test.json", "validation_paired.M_minus_shared.same_sign", False, 0,
     "nor does M beat its capacity-matched single-score control"),
    ("e27_adaptation_test.json", "validation_paired.S_minus_P.same_sign", False, 0,
     "nor does the selection objective beat ordinary prediction"),
    ("e27_adaptation_test.json", "strata.0.arms.P_n200_s20260910.achieved_at_1", 0.03929,
     0.00002, "at 200 training groups adaptation is worse than not adapting"),
    ("e27_adaptation_test.json", "strata.0.arms.G_s20260910.achieved_at_1", 0.03968,
     0.00002, "geometry alone does not beat OptiPrime"),
    ("e27_adaptation_test.json", "strata.0.paired.G_s20260910_minus_op.two_sided_p", 0.134,
     0.005, "at p = 0.134"),
    ("e28_source_retention.json", "mean_spearman_change_by_arm.P", -0.0287, 0.0005,
     "full-budget ordinary fine-tuning gives up 0.029 source Spearman"),
    ("e28_source_retention.json", "mean_spearman_change_by_arm.S", -0.0075, 0.0005,
     "where the selection-head arm gives up only 0.008"),
    ("e28_source_retention.json", "mean_spearman_change_by_arm.shared", -0.0561, 0.0010,
     "and the shared-trunk control forgets most, 0.056"),
]


def dig(obj, path: str):
    for part in path.split("."):
        obj = obj[int(part)] if part.isdigit() else obj[part]
    return obj


def main() -> int:
    fails = []
    for fname, path, expect, tol, prose in CLAIMS:
        f = OUT / fname
        if not f.exists():
            fails.append(f"MISSING {fname} (for: {prose})")
            continue
        try:
            got = dig(json.loads(f.read_text()), path)
        except (KeyError, IndexError, TypeError) as exc:
            fails.append(f"NO PATH {fname}:{path} ({exc}) (for: {prose})")
            continue
        if isinstance(expect, (bool, str)) or tol == 0:
            ok = got == expect
        else:
            ok = abs(got - expect) <= tol
        if not ok:
            fails.append(f"DRIFT {fname}:{path} artefact={got!r} report={expect!r} "
                         f"(for: {prose})")
    print(f"checked {len(CLAIMS)} claims, {len(fails)} problems")
    for f in fails:
        print(" ", f)
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
